# Data Cleaning – Labor Law & NDA Clauses

In [ ]:
import pandas as pd

file_path = "/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/Book1١.xlsx"   # غيّريه لاسم ملفك

df = pd.read_excel(file_path)

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

for col in df.columns:
    df[col] = df[col].astype(str).str.strip()

df.to_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step1_clean.xlsx", index=False)

print("تم تنظيف أولي وحفظ الملف: contracts_step1_clean.xlsx")
print(df.head())

تم تنظيف أولي وحفظ الملف: contracts_step1_clean.xlsx
                   field              title_ar              category required  \
0  contract_written_copy  نسخة مكتوبة من العقد    general_provisions      نعم
1       probation_period          فترة التجربة        contract_terms      نعم
2    probation_extension    تمديد فترة التجربة        contract_terms       لا
3              job_title        المسمى الوظيفي       job_information      نعم
4             job_duties       المهام الوظيفية  employee_obligations      نعم

                  risk_if_missing                             description  \
0  صعوبة إثبات الحقوق والالتزامات   يجب وجود عقد واضح وتسليم نسخة للطرفين
1   نزاع عند الإنهاء خلال التجربة         تحديد مدة التجربة وشروطها بوضوح
2                 تمديد غير مشروع  لا يتم التمديد إلا وفق النظام والاتفاق
3      تكليف بمهام غير متفق عليها           تحديد الوظيفة الأساسية للعامل
4  استغلال العامل بمهام غير واضحة       تحديد المسؤوليات والمهام المطلوبة

           keywords  reference
0   نسخة، عقد مكتوب  المادة 17
1  تجربة، probation  المادة 19
2       تمديد تجربة  المادة 19
3       وظيفة، مسمى  المادة 18
4      مهام، duties  المادة 18

In [51]:

print("تم تنظيف أولي وحفظ الملف: contracts_step1_clean.xlsx")

df.head()

تم تنظيف أولي وحفظ الملف: contracts_step1_clean.xlsx

,field,title_ar,category,required,risk_if_missing,description,keywords,reference
0,contract_written_copy,نسخة مكتوبة من العقد,general_provisions,نعم,صعوبة إثبات الحقوق والالتزامات,يجب وجود عقد واضح وتسليم نسخة للطرفين,نسخة، عقد مكتوب,المادة 17
1,probation_period,فترة التجربة,contract_terms,نعم,نزاع عند الإنهاء خلال التجربة,تحديد مدة التجربة وشروطها بوضوح,تجربة، probation,المادة 19
2,probation_extension,تمديد فترة التجربة,contract_terms,لا,تمديد غير مشروع,لا يتم التمديد إلا وفق النظام والاتفاق,تمديد تجربة,المادة 19
3,job_title,المسمى الوظيفي,job_information,نعم,تكليف بمهام غير متفق عليها,تحديد الوظيفة الأساسية للعامل,وظيفة، مسمى,المادة 18
4,job_duties,المهام الوظيفية,employee_obligations,نعم,استغلال العامل بمهام غير واضحة,تحديد المسؤوليات والمهام المطلوبة,مهام، duties,المادة 18

In [ ]:
 
df = pd.read_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step1_clean.xlsx")

df["required"] = (
    df["required"]
    .astype(str)
    .str.strip()
    .replace({
        "نعم ": "نعم",
        " نعم": "نعم",
        "لا ": "لا",
        " لا": "لا",
        "اختيارى": "اختياري",
        "إختياري": "اختياري",
        "نعم (لغير السعودي)": "نعم",
    })
)

df.loc[df["required"].str.contains("نعم", na=False), "required"] = "نعم"

df.loc[df["required"].str.contains("اختياري", na=False), "required"] = "اختياري"

df.loc[df["required"].str.fullmatch("لا", na=False), "required"] = "لا"

df.to_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step2_required_clean.xlsx", index=False)

print(df["required"].value_counts())
print("تم حفظ الملف: contracts_step2_required_clean.xlsx")

required
نعم        147
لا         147
اختياري      3
Name: count, dtype: int64
تم حفظ الملف: contracts_step2_required_clean.xlsx

In [ ]:

df = pd.read_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step2_required_clean.xlsx")

print("القيم الحالية في category:\n")
print(df["category"].value_counts(dropna=False))

القيم الحالية في category:

category
legal_compliance                49
compensation                    35
leave_benefits                  30
general_provisions              29
parties                         29
termination_exit                25
employee_obligations            21
contract_terms                  20
employer_rights                 19
work_schedule                   12
job_information                 11
confidentiality_restrictions     4
governance                       4
customer_rights                  4
operations                       3
marketing_compliance             1
security                         1
Name: count, dtype: int64

In [ ]:

df["category"] = (
    df["category"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df.to_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step3_category_clean.xlsx", index=False)

print("\nتم الحفظ: contracts_step3_category_clean.xlsx")

تم الحفظ: contracts_step3_category_clean.xlsx

In [ ]:
df = pd.read_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step3_category_clean.xlsx")

df["field"] = (
    df["field"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [ ]:
duplicates = df[df.duplicated(subset=["field"], keep=False)]

print("عدد الصفوف المكررة:", len(duplicates))
print("\nالصفوف المكررة:\n")
duplicates

عدد الصفوف المكررة: 49

الصفوف المكررة:

,field,title_ar,category,required,risk_if_missing,description,keywords,reference
0,contract_written_copy,نسخة مكتوبة من العقد,general_provisions,نعم,صعوبة إثبات الحقوق والالتزامات,يجب وجود عقد واضح وتسليم نسخة للطرفين,نسخة، عقد مكتوب,المادة 17
1,probation_period,فترة التجربة,contract_terms,نعم,نزاع عند الإنهاء خلال التجربة,تحديد مدة التجربة وشروطها بوضوح,تجربة، probation,المادة 19
7,basic_salary,الأجر الأساسي,compensation,نعم,نزاع مالي مباشر,تحديد الأجر الأساسي المتفق عليه,راتب، أجر,المادة 18
11,overtime_pay,أجر العمل الإضافي,compensation,لا,عدم دفع مقابل الإضافي,صرف أجر إضافي حسب النظام,أجر إضافي,المادة 22
14,annual_leave,الإجازة السنوية,leave_benefits,نعم,حرمان العامل من حقه,تحديد مدة الإجازة السنوية,إجازة سنوية,المادة 24
15,emergency_leave,الإجازات الطارئة,leave_benefits,لا,خلافات عند الغياب,تنظيم الإجازات الخاصة والطارئة,طارئة، غياب,المادة 24
16,sick_leave,الإجازة المرضية,leave_benefits,نعم,رفض إجازة المرض,تنظيم الإجازة المرضية والاستحقاق,مرضية,المادة 24
18,contract_duration,مدة العقد,contract_terms,نعم,خلاف حول انتهاء العقد,تحديد هل العقد محدد أو غير محدد,مدة، عقد,المادة 25
21,end_of_service_award,مكافأة نهاية الخدمة,termination_exit,نعم,نزاع بعد انتهاء العقد,تنظيم استحقاق نهاية الخدمة,نهاية خدمة,نظام العمل
37,grievance_right,حق الاعتراض على العقوبة,legal_compliance,نعم,انتقاص حقوق العامل,تمكين العامل من التظلم والاعتراض,اعتراض، تظلم,المادة 39
38,disciplinary_investigation,التحقيق قبل العقوبة,employer_rights,نعم,عقوبات غير عادلة,وجوب التحقيق قبل فرض الجزاء في الحالات اللازمة,تحقيق، عقوبة,المادة 38
76,annual_leave,الإجازة السنوية,leave_benefits,نعم,مطالبة مالية,استحقاق الإجازة السنوية ومدتها,سنوية، رصيد,المادة 33
77,emergency_leave,الإجازة الطارئة,leave_benefits,لا,خلافات تشغيلية,تنظيم الإجازة الطارئة إن وجدت,طارئة,سياسة داخلية
78,sick_leave,الإجازة المرضية,leave_benefits,نعم,مطالبة نظامية,شروط الإجازة المرضية ومدتها,مرضية، تقرير,المادة 41
79,maternity_leave,إجازة الوضع والأمومة,leave_benefits,نعم,مخالفة حقوق المرأة,حقوق الموظفة في إجازة الوضع,أمومة، وضع,المادة 50
82,wage_payment_method,طريقة صرف الأجر,compensation,نعم,نزاع مالي,تحديد وسيلة وموعد دفع الرواتب,راتب، تحويل,المادة 15
83,overtime_pay,أجر العمل الإضافي,compensation,نعم,مطالبات مالية,احتساب أجر الساعات الإضافية,إضافي، overtime,المادة 29
92,end_of_service_award,مكافأة نهاية الخدمة,termination_exit,نعم,مطالبات مالية عالية,احتساب واستحقاق مكافأة نهاية الخدمة,نهاية خدمة,المادة 40
145,contract_type,نوع العقد,contract_terms,نعم,خلاف حول طبيعة العلاقة,تحديد ما إذا كان العقد محدد المدة أو غير محدد ...,"نوع العقد، fixed-term, open-ended",نموذج عقد العمل – البند 1
146,contract_execution_date,تاريخ إبرام العقد,general_provisions,نعم,نزاع حول بداية الالتزامات,تحديد تاريخ توقيع وإبرام العقد بين الطرفين,تاريخ الإبرام، execution date,نموذج عقد العمل – البند 1
217,contract_written_copy,نسخة مكتوبة من العقد,general_provisions,نعم,صعوبة إثبات الحقوق والالتزامات,يجب وجود عقد واضح وتسليم نسخة لكل طرف,نسخة، عقد مكتوب,المادة 17
218,probation_period,فترة التجربة,contract_terms,اختياري,اعتبار العامل مثبتًا فوراً بدون حق التجربة,تحديد مدة لتجربة الموظف لا تزيد عن 90 يوماً,تجربة، اختبار,المادة 19
219,basic_salary,الأجر الأساسي,compensation,نعم,بطلان العقد وتدني كفاءة الامتثال المالي,المبلغ المتفق عليه كمقابل للعمل دون البدلات,أجر، راتب، ريال,المادة 18
221,annual_leave,الإجازة السنوية,leave_benefits,نعم,التعرض لغرامات نظامية وحرمان العامل من الراحة,استحقاق العامل إجازة مدفوعة عن كل عام,إجازة سنوية، رصيد,المادة 24
222,social_insurance,التأمينات الاجتماعية,legal_compliance,نعم,ملاحقات قانونية وغرامات من مؤسسة التأمينات,التزام صاحب العمل بتسجيل العامل في التأمينات,تأمينات، GOSI، اشتراكات,البند رابعاً
223,job_description,موضوع العقد,job_information,نعم,تكليف العامل بمهام غير مهنته الموثقة,تحديد طبيعة العمل والمهام المسندة للعامل,مهام، مسمى، عمل,المادة 18
224,medical_insurance,التأمين الصحي,legal_compliance,نعم,إيقاف خدمات المنشأة ومخالفة مجلس الضمان,توفير الرعاية الطبية للعامل وأسرته,تأمين، طبي، علاج,البند رابعاً
225,safety_obligations,تعليمات السلامة,legal_compliance,نعم,وقوع إصابات عمل ومسؤولية قانونية كاملة,التزام العامل باتباع قواعد الصحة والمهنة,سلامة، وقاية، أخطار,البند رابعاً
226,notice_period,مهلة الإشعار,termination_exit,نعم,إنهاء مفاجئ يوجب دفع تعويض مالي,المدة التي يبلغ فيها أحد الطرفين الآخر بالرغبة...,إشعار، إنهاء، مهلة,المادة 75
227,confidentiality,المحافظة على الأسرار,employee_obligations,نعم,تسريب أسرار المنشأة وإلحاق الضرر بها,التزام الموظف بعدم إفشاء أسرار العمل,أسرار، خصوصية، كتمان,البند رابعاً
228,working_location,مكان العمل,job_information,نعم,النزاع حول مقرات العمل والنقل التعسفي,تحديد المدينة أو الموقع الجغرافي للعمل,مكان، مقر، مدينة,المادة 18
232,contract_written_copy,نسخة مكتوبة من العقد,general_provisions,نعم,صعوبة إثبات الحقوق والالتزامات,يجب وجود عقد واضح من نسختين أصليتين وتسليم نسخ...,نسخة، عقد مكتوب، نسخة لكل طرف,المادة 17
233,probation_period,فترة التجربة,contract_terms,اختياري,اعتبار العامل مثبتًا فوراً وعدم القدرة على إنه...,تحديد مدة لتجربة الموظف للتحقق من كفاءته (لا ت...,تجربة، 90 يوماً، اختبار,المادة 19
234,basic_salary,الأجر الأساسي,compensation,نعم,بطلان العقد ومخالفة صريحة لنظام العمل,المبلغ المالي الثابت المتفق عليه مقابل العمل (...,أجر، راتب، ريال سعودي,المادة 18
238,social_insurance,التأمينات الاجتماعية,legal_compliance,نعم,غرامات مالية ضخمة وإيقاف خدمات المنشأة,التزام صاحب العمل بتسجيل العامل في المؤسسة الع...,تأمينات، GOSI، اشتراكات,رابعاً: التزامات صاحب العمل
239,medical_insurance,التأمين الصحي,legal_compliance,نعم,مخالفة نظام الضمان الصحي وتحمل تكاليف علاج الموظف,توفير الرعاية الطبية للعامل (وأسرته إن وجد) وف...,تأمين طبي، رعاية صحية,رابعاً: التزامات صاحب العمل
240,safety_obligations,تعليمات السلامة,legal_compliance,نعم,مسؤولية قانونية كاملة عند وقوع إصابات عمل,التزام العامل بكافة قواعد السلامة المهنية واست...,سلامة، وقاية، مخاطر، أخطار,رابعاً: التزامات الطرف الثاني
241,maternity_leave,إجازة الوضع,leave_benefits,نعم,انتهاك حقوق المرأة العاملة وتعرض المنشأة للمساءلة,إجازة بأجر كامل للمرأة العاملة لمدة 10 أسابيع ...,وضع، 10 أسابيع، ولادة,البند 5 من نموذج العقد
242,notice_period,مهلة الإشعار,termination_exit,نعم,إنهاء مفاجئ يترتب عليه دفع تعويض مادي مساوٍ للمدة,المدة اللازمة لإخطار الطرف الآخر برغبة إنهاء ا...,إشعار، إنهاء، مهلة، ستون يوماً,المادة 75
243,working_location,مكان العمل,job_information,نعم,ادعاء العامل بالنقل التعسفي خارج نطاق الاتفاق,تحديد المقر أو المدينة التي سيؤدي فيها العامل ...,مكان العمل، مدينة، موقع,المادة 18
244,confidentiality,المحافظة على الأسرار,employee_obligations,نعم,ضياع حقوق المنشأة عند تسريب بيانات العملاء أو ...,التزام العامل بعدم إفشاء أسرار العمل حتى بعد ا...,أسرار، خصوصية، كتمان,رابعاً: التزامات الطرف الثاني
246,job_description,موضوع العقد والمهام,job_information,نعم,رفض العامل لمهام إضافية لعدم ذكرها في العقد,تحديد المسمى الوظيفي والمهام التي سيباشرها الم...,مهام، وظيفة، مسمى,المادة 18
247,contract_type,نوع العقد,contract_terms,نعم,غموض طبيعة العلاقة التعاقدية,تحديد ما إذا كان العقد محدد المدة أو غير محدد ...,نوع العقد، محدد، غير محدد,نموذج عقد العمل
249,contract_duration,مدة العقد,contract_terms,نعم,خلاف حول نهاية العقد أو تجديده,تحديد مدة العقد إن كان محدد المدة,مدة، نهاية، تجديد,المادة 25
250,wage_payment_method,طريقة صرف الأجر,compensation,نعم,نزاع في وسيلة السداد وإثبات الدفع,تحديد هل السداد تحويل بنكي أو وسيلة معتمدة أخرى,تحويل، بنك، صرف,نموذج عقد العمل
251,end_of_service_award,مكافأة نهاية الخدمة,termination_exit,نعم,مطالبة مالية كبيرة عند انتهاء العلاقة,تنظيم استحقاق مكافأة نهاية الخدمة,نهاية خدمة، مكافأة,نظام العمل
252,grievance_right,حق التظلم والاعتراض,legal_compliance,نعم,ضعف حماية العامل إجرائيًا,تمكين العامل من الاعتراض على الجزاء,تظلم، اعتراض,المادة 39
253,disciplinary_investigation,التحقيق قبل العقوبة,employer_rights,نعم,فرض عقوبات غير عادلة,وجوب التحقيق قبل توقيع العقوبة في الحالات اللازمة,تحقيق، جزاء,المادة 38
254,contract_execution_date,تاريخ إبرام العقد,general_provisions,نعم,نزاع حول بدء الالتزامات,تاريخ توقيع وإبرام العقد بين الطرفين,إبرام، توقيع، تاريخ,نموذج العقد

In [ ]:
fields_to_replace = [
    "contract_written_copy",
    "probation_period",
    "basic_salary",
    "overtime_pay",
    "annual_leave",
    "emergency_leave",
    "sick_leave",
    "contract_duration",
    "end_of_service_award",
    "grievance_right",
    "disciplinary_investigation",
    "contract_type",
    "contract_execution_date",
    "social_insurance",
    "job_description",
    "medical_insurance",
    "safety_obligations",
    "notice_period",
    "confidentiality",
    "working_location",
    "maternity_leave",
    "wage_payment_method",
]

df = df[~df["field"].isin(fields_to_replace)].copy()

manual_rows = [
    {
        "field": "contract_written_copy",
        "title_ar": "نسخة مكتوبة من العقد",
        "category": "general_provisions",
        "required": "نعم",
        "risk_if_missing": "صعوبة إثبات الحقوق والالتزامات",
        "description": "يجب وجود عقد واضح من نسختين أصليتين وتسليم نسخة لكل طرف",
        "keywords": "نسخة، عقد مكتوب، نسخة لكل طرف",
        "reference": "المادة 17",
    },
    {
        "field": "probation_period",
        "title_ar": "فترة التجربة",
        "category": "contract_terms",
        "required": "اختياري",
        "risk_if_missing": "اعتبار العامل مثبتًا فوراً وعدم القدرة على إنهاء العقد بسهولة",
        "description": "تحديد مدة لتجربة الموظف للتحقق من كفاءته على ألا تزيد عن 90 يوماً",
        "keywords": "تجربة، 90 يوماً، اختبار",
        "reference": "المادة 19",
    },
    {
        "field": "basic_salary",
        "title_ar": "الأجر الأساسي",
        "category": "compensation",
        "required": "نعم",
        "risk_if_missing": "بطلان العقد ومخالفة صريحة لنظام العمل",
        "description": "المبلغ المالي الثابت المتفق عليه مقابل العمل سواء شهرياً أو أسبوعياً دون البدلات",
        "keywords": "أجر، راتب، ريال سعودي",
        "reference": "المادة 18",
    },
    {
        "field": "overtime_pay",
        "title_ar": "أجر العمل الإضافي",
        "category": "compensation",
        "required": "نعم",
        "risk_if_missing": "مطالبات مالية وعدم دفع مقابل الإضافي",
        "description": "احتساب وصرف أجر الساعات الإضافية وفق النظام",
        "keywords": "إضافي، overtime، أجر إضافي",
        "reference": "المادة 22، المادة 29",
    },
    {
        "field": "annual_leave",
        "title_ar": "الإجازة السنوية",
        "category": "leave_benefits",
        "required": "نعم",
        "risk_if_missing": "حرمان العامل من حقه والتعرض لمطالبات أو غرامات نظامية",
        "description": "استحقاق العامل إجازة سنوية مدفوعة وتحديد مدتها ورصيدها وفق النظام",
        "keywords": "إجازة سنوية، سنوية، رصيد",
        "reference": "المادة 24، المادة 33",
    },
    {
        "field": "emergency_leave",
        "title_ar": "الإجازة الطارئة",
        "category": "leave_benefits",
        "required": "لا",
        "risk_if_missing": "خلافات تشغيلية عند الغياب",
        "description": "تنظيم الإجازة الطارئة أو الخاصة إن وجدت",
        "keywords": "طارئة، غياب",
        "reference": "المادة 24، سياسة داخلية",
    },
    {
        "field": "sick_leave",
        "title_ar": "الإجازة المرضية",
        "category": "leave_benefits",
        "required": "نعم",
        "risk_if_missing": "رفض إجازة المرض أو مطالبات نظامية",
        "description": "تنظيم وشروط الإجازة المرضية ومدتها واستحقاقها",
        "keywords": "مرضية، تقرير",
        "reference": "المادة 24، المادة 41",
    },
    {
        "field": "contract_duration",
        "title_ar": "مدة العقد",
        "category": "contract_terms",
        "required": "نعم",
        "risk_if_missing": "خلاف حول انتهاء العقد أو تجديده",
        "description": "تحديد مدة العقد وبيان ما إذا كان محدد المدة أو غير محدد، وشروط التجديد إن وجدت",
        "keywords": "مدة، عقد، نهاية، تجديد",
        "reference": "المادة 25",
    },
    {
        "field": "end_of_service_award",
        "title_ar": "مكافأة نهاية الخدمة",
        "category": "termination_exit",
        "required": "نعم",
        "risk_if_missing": "مطالبات مالية كبيرة ونزاع عند انتهاء العلاقة",
        "description": "تنظيم احتساب واستحقاق مكافأة نهاية الخدمة وفق نظام العمل",
        "keywords": "نهاية خدمة، مكافأة",
        "reference": "نظام العمل، المادة 40",
    },
    {
        "field": "grievance_right",
        "title_ar": "حق التظلم والاعتراض",
        "category": "legal_compliance",
        "required": "نعم",
        "risk_if_missing": "انتقاص حقوق العامل وضعف الحماية الإجرائية",
        "description": "تمكين العامل من التظلم والاعتراض على الجزاء",
        "keywords": "اعتراض، تظلم",
        "reference": "المادة 39",
    },
    {
        "field": "disciplinary_investigation",
        "title_ar": "التحقيق قبل العقوبة",
        "category": "employer_rights",
        "required": "نعم",
        "risk_if_missing": "فرض عقوبات غير عادلة",
        "description": "وجوب التحقيق قبل توقيع العقوبة أو فرض الجزاء في الحالات اللازمة",
        "keywords": "تحقيق، عقوبة، جزاء",
        "reference": "المادة 38",
    },
    {
        "field": "contract_type",
        "title_ar": "نوع العقد",
        "category": "contract_terms",
        "required": "نعم",
        "risk_if_missing": "غموض طبيعة العلاقة التعاقدية",
        "description": "تحديد ما إذا كان العقد محدد المدة أو غير محدد المدة أو لبعض الوقت",
        "keywords": "نوع العقد، محدد، غير محدد، fixed-term, open-ended",
        "reference": "نموذج عقد العمل – البند 1",
    },
    {
        "field": "contract_execution_date",
        "title_ar": "تاريخ إبرام العقد",
        "category": "general_provisions",
        "required": "نعم",
        "risk_if_missing": "نزاع حول بدء الالتزامات",
        "description": "تحديد تاريخ توقيع وإبرام العقد بين الطرفين",
        "keywords": "إبرام، توقيع، تاريخ",
        "reference": "نموذج عقد العمل – البند 1، نموذج العقد",
    },
    {
        "field": "social_insurance",
        "title_ar": "التأمينات الاجتماعية",
        "category": "legal_compliance",
        "required": "نعم",
        "risk_if_missing": "غرامات مالية ومطالبات نظامية",
        "description": "التزام صاحب العمل بتسجيل العامل في المؤسسة العامة للتأمينات الاجتماعية وسداد الاشتراكات حسب النظام",
        "keywords": "تأمينات، GOSI، اشتراكات",
        "reference": "البند رابعاً، رابعاً: التزامات صاحب العمل",
    },
    {
        "field": "job_description",
        "title_ar": "موضوع العقد والمهام",
        "category": "job_information",
        "required": "نعم",
        "risk_if_missing": "تكليف العامل بمهام غير مهنته الموثقة أو رفض العامل لمهام غير محددة",
        "description": "تحديد المسمى الوظيفي وطبيعة العمل والمهام المسندة للعامل بدقة",
        "keywords": "مهام، وظيفة، مسمى، عمل",
        "reference": "المادة 18",
    },
    {
        "field": "medical_insurance",
        "title_ar": "التأمين الصحي",
        "category": "legal_compliance",
        "required": "نعم",
        "risk_if_missing": "مخالفة نظام الضمان الصحي وتحمل تكاليف علاج الموظف",
        "description": "توفير الرعاية الطبية للعامل وأسرته إن وجد وفق النظام",
        "keywords": "تأمين طبي، رعاية صحية، علاج",
        "reference": "البند رابعاً، رابعاً: التزامات صاحب العمل",
    },
    {
        "field": "safety_obligations",
        "title_ar": "تعليمات السلامة",
        "category": "legal_compliance",
        "required": "نعم",
        "risk_if_missing": "وقوع إصابات عمل ومسؤولية قانونية كاملة",
        "description": "الالتزام بقواعد السلامة المهنية واستخدام أدوات الوقاية ومتطلبات الصحة المهنية",
        "keywords": "سلامة، وقاية، مخاطر، أخطار",
        "reference": "البند رابعاً، رابعاً: التزامات الطرف الثاني",
    },
    {
        "field": "notice_period",
        "title_ar": "مهلة الإشعار",
        "category": "termination_exit",
        "required": "نعم",
        "risk_if_missing": "إنهاء مفاجئ يترتب عليه دفع تعويض",
        "description": "المدة اللازمة لإخطار الطرف الآخر برغبة إنهاء العقد، مثل 60 يوماً وفق النظام",
        "keywords": "إشعار، إنهاء، مهلة، ستون يوماً",
        "reference": "المادة 75",
    },
    {
        "field": "confidentiality",
        "title_ar": "المحافظة على الأسرار",
        "category": "employee_obligations",
        "required": "نعم",
        "risk_if_missing": "تسريب أسرار المنشأة وضياع حقوقها",
        "description": "التزام العامل بعدم إفشاء أسرار العمل أو بياناته أثناء العقد وبعد انتهائه",
        "keywords": "أسرار، خصوصية، كتمان",
        "reference": "البند رابعاً، رابعاً: التزامات الطرف الثاني",
    },
    {
        "field": "working_location",
        "title_ar": "مكان العمل",
        "category": "job_information",
        "required": "نعم",
        "risk_if_missing": "النزاع حول مقر العمل أو النقل التعسفي",
        "description": "تحديد المقر أو المدينة أو الموقع الجغرافي الذي سيؤدي فيه العامل مهامه",
        "keywords": "مكان العمل، مدينة، موقع، مقر",
        "reference": "المادة 18",
    },
    {
        "field": "maternity_leave",
        "title_ar": "إجازة الوضع",
        "category": "leave_benefits",
        "required": "نعم",
        "risk_if_missing": "انتهاك حقوق المرأة العاملة",
        "description": "حقوق الموظفة في إجازة الوضع بأجر كامل وفق النظام",
        "keywords": "وضع، أمومة، 10 أسابيع، ولادة",
        "reference": "المادة 50، البند 5 من نموذج العقد",
    },
    {
        "field": "wage_payment_method",
        "title_ar": "طريقة صرف الأجر",
        "category": "compensation",
        "required": "نعم",
        "risk_if_missing": "نزاع في وسيلة السداد وإثبات الدفع",
        "description": "تحديد وسيلة وموعد صرف الرواتب، مثل التحويل البنكي أو أي وسيلة معتمدة",
        "keywords": "راتب، تحويل، بنك، صرف",
        "reference": "المادة 15، نموذج عقد العمل",
    },
]

manual_df = pd.DataFrame(manual_rows)

df = pd.concat([df, manual_df], ignore_index=True)

df = df.sort_values(by=["category", "field"], na_position="last").reset_index(drop=True)

df.to_excel("/Users/moojalgoot/Desktop/capstone-project-team/untitled folder 4/contracts_step4_manual_merged.xlsx", index=False)

print("تم حفظ الملف: contracts_step4_manual_merged.xlsx")
print("عدد الصفوف النهائي:", len(df))

تم حفظ الملف: contracts_step4_manual_merged.xlsx
عدد الصفوف النهائي: 270

In [ ]:
for col in df.columns:
    df[col] = df[col].astype(str).str.strip()

df = df.replace("nan", "")

In [ ]:
for i in df["field"]:
    print(i)

allowances
annual_bonus_non_saudi
bank_name
basic_salary
basic_wage_amount
commission_clause
commission_due_date
commission_percentage
deductions_policy
employee_iban
gosi_deduction
housing_allowance
housing_allowance_non_saudi
in_kind_benefits
in_kind_benefits_description
in_kind_benefits_due_date
net_wage
other_cash_allowances
overtime_pay
pay_commission_if_agreed
pay_in_kind_benefits_if_agreed
pay_via_approved_method
recruitment_residency_fees
setup_allowance
total_wage
transport_allowance
transport_allowance_non_saudi
wage_deduction_penalty
wage_payment_date
wage_payment_method
wage_protection_compliance
confidentiality_clause
data_privacy_employee
intellectual_property_clause
non_compete_clause
contract_duration
contract_end_date
contract_start_date
contract_type
contract_void_if_no_start
no_full_time_conversion
part_time_ratio
part_time_work
probation_extension
probation_period
remote_work_clause
renewal_clause
seasonal_work
start_within_15_days
temporary_contract_max_duration
trainee_contract
client_contract_required
client_rights_policy
complaint_sla_days
complaints_system
absence_policy
assist_in_emergencies
behavior_violations
care_for_tools
conduct_rules
confidentiality
direct_supervision_clause
equipment_misuse
good_conduct_ethics
intellectual_property
job_duties
lateness_policy
medical_exam_when_requested
perform_assigned_work
performance_evaluation
promotion_policy
training_obligation
training_program_clause
worker_duties
workplace_conduct_penalties
disciplinary_actions
disciplinary_investigation
disciplinary_penalties
disciplinary_procedure_clause
employer_duties
investigation_process
penalties_schedule
penalty_proportionality
policy_acknowledgment
progressive_discipline
suspension_from_work
suspension_penalty
temporary_assignment
transfer_work_location
violations_table
warning_before_penalty
work_tools_provision
written_warning
amendment_documentation
arabic_contract_copies
contract_data_amendment
contract_execution_date
contract_execution_day
contract_execution_location
contract_number
contract_written_copy
dispute_resolution_clause
electronic_contract_copy
employee_acknowledgment_of_policies
execution_document_clause
governing_language
hijri_calendar_clause
labor_court_jurisdiction
legal_capacity
no_amendment_without_written_agreement
no_unofficial_notices
notice_by_email_or_registered_mail
notice_delivery_method
offline_notice_fallback
optional_additional_terms
parties_acknowledgment
portal_documentation
preamble_clause
saudi_law_governing
closure_exit_plan
compliance_department
hr_independent_department
internal_audit_department
job_description
job_grade
job_number
job_rank_level
job_title
work_domain
work_location
work_type
working_location
accommodation_conditions
annual_leave
annual_leave_21
annual_leave_30
annual_leave_compensation
annual_leave_days
annual_leave_postponement
annual_leave_scheduling
bereavement_leave
emergency_leave
exam_leave
health_care
leave_types
maternity_leave
preventive_health_care
sick_leave
social_services
transport_conditions
transport_provision
transportation_housing
travel_tickets
unpaid_leave
weekly_rest_day
worker_housing_standards
workplace_housing
accessibility_tools
anti_harassment_policy
applicable_law_clause
bank_guarantee_amount
branch_approval_required
cancellation_conditions
complaint_channel
complaint_non_retaliation
confidentiality_violation
data_update_30_days
disability_accommodation
equality_non_discrimination
first_aid_kit
first_aid_provision
foreign_investor_docs
gosi_registration
grievance_deadline
grievance_right
harassment_penalty
harassment_protection
hazardous_work_restriction
health_safety_rules
injury_reporting
labor_services_license
license_amendment_request
license_validity_years
licensing_entity_type
medical_insurance
minor_employment_age
minor_night_work_ban
no_double_penalty
outsourcing_limits
outsourcing_worker_rights
ownership_change_approval
paid_capital_minimum
permitted_activities
platform_registration
recruitment_fees_ban
recruitment_license_rules
renewal_deadline_days
safety_obligations
safety_violations
social_insurance
suspension_conditions
women_night_work_rules
advertising_controls
accommodation_transport_for_workers
service_quality_standards
worker_file_records
employee_birth_date
employee_email
employee_fax
employee_gender
employee_id_number
employee_id_type
employee_marital_status
employee_mobile_number
employee_name
employee_national_address
employee_nationality
employee_passport_number
employee_po_box
employee_postal_code
employee_selected_address
employer_entity_type
employer_fax
employer_hrsd_id
employer_name
employer_national_address
employer_official_email
employer_phone
employer_po_box
employer_postal_code
employer_selected_address
employer_signatory_capacity
employer_signatory_id
employer_signatory_name
employer_unified_national_no
cyber_data_protection
article80_termination_clause
article81_employee_exit
company_property_return
compensation_for_no_notice
dismissal_penalty
document_handover
end_of_service_award
final_settlement
mutual_termination_clause
no_eos_for_part_time
no_eos_for_temporary
no_notice_during_probation
notice_period
resignation_process
temporary_contract_end_by_duration
temporary_termination_cases
termination_cases
termination_causes
termination_notice
transport_costs
travel_cost_return
unjustified_termination_compensation
assign_overtime_in_writing
attendance_absence_rules
attendance_penalties
attendance_system
break_times
no_overtime_for_part_time
overtime_work
rest_days_per_week
work_hours_limit
work_schedule_detail
working_hours
working_hours_daily

In [ ]:

field_map = {
  
    "basic_wage_amount": "basic_salary",
    "wage_payment_method": "wage_payment_method",
    "wage_payment_date": "wage_payment_date",
    "gosi_deduction": "social_insurance",
    "gosi_registration": "social_insurance",
    "wage_protection_compliance": "wage_payment_method",

    "housing_allowance_non_saudi": "housing_allowance",
    "transport_allowance_non_saudi": "transport_allowance",

   
    "confidentiality_clause": "confidentiality",
    "data_privacy_employee": "confidentiality",
    "intellectual_property_clause": "intellectual_property",

  
    "contract_start_date": "contract_execution_date",
    "working_hours": "working_hours_daily",
    "work_hours_limit": "working_hours_daily",
    "work_schedule_detail": "working_hours_daily",

    "temporary_contract_max_duration": "contract_duration",
    "temporary_contract_end_by_duration": "contract_duration",
    "temporary_termination_cases": "termination_cases",


    "job_description": "job_duties",
    "perform_assigned_work": "job_duties",
    "worker_duties": "job_duties",

    "conduct_rules": "good_conduct_ethics",
    "workplace_conduct_penalties": "good_conduct_ethics",
    "behavior_violations": "good_conduct_ethics",

    "care_for_tools": "work_tools_provision",
    "equipment_misuse": "work_tools_provision",

    "training_program_clause": "training_obligation",

    "disciplinary_actions": "disciplinary_penalties",
    "penalties_schedule": "disciplinary_penalties",
    "violations_table": "disciplinary_penalties",
    "written_warning": "warning_before_penalty",
    "progressive_discipline": "disciplinary_penalties",
    "suspension_penalty": "suspension_from_work",
    "investigation_process": "disciplinary_investigation",

   
    "electronic_contract_copy": "contract_written_copy",
    "arabic_contract_copies": "contract_written_copy",

    "notice_delivery_method": "notice_by_email_or_registered_mail",
    "no_unofficial_notices": "notice_by_email_or_registered_mail",
    "offline_notice_fallback": "notice_by_email_or_registered_mail",

    "portal_documentation": "contract_written_copy",
    "amendment_documentation": "contract_data_amendment",

    "saudi_law_governing": "applicable_law_clause",
    "labor_court_jurisdiction": "dispute_resolution_clause",

   
    "working_location": "work_location",
    "job_number": "job_title",
    "job_rank_level": "job_grade",


    "annual_leave_21": "annual_leave",
    "annual_leave_30": "annual_leave",
    "annual_leave_days": "annual_leave",
    "leave_types": "annual_leave",

    "preventive_health_care": "health_care",
    "medical_insurance": "health_care",

    "transport_conditions": "transport_provision",
    "transportation_housing": "transport_provision",
    "workplace_housing": "accommodation_conditions",
    "worker_housing_standards": "accommodation_conditions",

    "safety_obligations": "health_safety_rules",
    "first_aid_kit": "first_aid_provision",
    "harassment_protection": "anti_harassment_policy",
    "harassment_penalty": "anti_harassment_policy",
    "grievance_deadline": "grievance_right",

    "employee_selected_address": "employee_national_address",
    "employer_selected_address": "employer_national_address",

  
    "termination_causes": "termination_cases",
    "termination_notice": "notice_period",
    "travel_cost_return": "transport_costs",
}

In [62]:
df["field"] = df["field"].replace(field_map)

In [ ]:
duplicates = df[df.duplicated(subset=["field"], keep=False)]

print("عدد الصفوف المكررة:", len(duplicates))
print("\nالصفوف المكررة:\n")
duplicates

عدد الصفوف المكررة: 103

الصفوف المكررة:

,field,title_ar,category,required,risk_if_missing,description,keywords,reference
3,basic_salary,الأجر الأساسي,compensation,نعم,بطلان العقد ومخالفة صريحة لنظام العمل,المبلغ المالي الثابت المتفق عليه مقابل العمل س...,أجر، راتب، ريال سعودي,المادة 18
4,basic_salary,قيمة الأجر الأساسي,compensation,نعم,نزاع مباشر على الراتب,المبلغ الأساسي الذي يبنى عليه الأجر والحقوق ذا...,أجر أساسي، basic wage,نموذج عقد العمل – البند 9
10,social_insurance,استقطاع التأمينات الاجتماعية,compensation,نعم,نزاع في صافي الأجر,تحديد نسبة أو مقدار الاستقطاع الخاص بالمؤسسة ا...,GOSI، تأمينات,نموذج عقد العمل – البند 9
11,housing_allowance,بدل السكن,compensation,لا,نزاع على المزايا,تحديد بدل السكن إذا اتفق الطرفان عليه,بدل سكن,نموذج عقد العمل – البند 9
12,housing_allowance,بدل السكن لغير السعودي,compensation,لا,نزاع بدل,بدل سكن سنوي أو سكن مؤثث بديل,سكن، غير سعودي,نموذج غير السعودي
...,...,...,...,...,...,...,...,...
256,transport_costs,تكلفة العودة,termination_exit,نعم,تحمل المنشأة غرامات ترحيل أو تذاكر عودة قسرية,تحمل صاحب العمل تكاليف عودة العامل لبلده بعد ا...,تذكرة عودة، عودة، سفر,رابعاً: التزامات صاحب العمل
266,working_hours_daily,ساعات العمل,work_schedule,نعم,مخالفة الحد الأقصى للنظام وضياع الأجر الإضافي,تحديد عدد الساعات اليومية أو الأسبوعية,ساعات، دوام، وقت,المادة 23
267,working_hours_daily,تفاصيل أوقات العمل,work_schedule,نعم,نزاع دوام,ساعات العمل والراحة الأسبوعية واليومية,دوام، ساعات,المادة 26
268,working_hours_daily,ساعات العمل,work_schedule,نعم,تشغيل العامل أكثر من الحد النظامي واستحقاق أجو...,تحديد الساعات اليومية (مثلاً 8 ساعات) أو الأسب...,ساعات، دوام، يومياً، أسبوعياً,المادة 23
269,working_hours_daily,ساعات العمل اليومية,work_schedule,نعم,تشغيل زائد مخالف,تحديد عدد ساعات العمل اليومية,ساعات، دوام,المادة 23

In [64]:
field_name = "annual_leave"  

print(df[df["field"] == field_name][[
    "field",
    "title_ar",
    "category",
    "required",
    "risk_if_missing",
    "description",
    "keywords",
    "reference"
]].to_string())

            field                  title_ar        category required                                        risk_if_missing                                                          description                         keywords                  reference
133  annual_leave           الإجازة السنوية  leave_benefits      نعم  حرمان العامل من حقه والتعرض لمطالبات أو غرامات نظامية    استحقاق العامل إجازة سنوية مدفوعة وتحديد مدتها ورصيدها وفق النظام         إجازة سنوية، سنوية، رصيد       المادة 24، المادة 33
134  annual_leave  الإجازة السنوية (21 يوم)  leave_benefits      نعم   مخالفة الحد الأدنى للإجازات وغرامات من وزارة الموارد          يستحق العامل إجازة سنوية لا تقل مدتها عن 21 يوماً عن كل عام            إجازة سنوية، 21 يوماً                  المادة 24
135  annual_leave  الإجازة السنوية (30 يوم)  leave_benefits      نعم        حرمان العامل من زيادات قانونية مستحقة بالأقدمية  تزيد الإجازة لتصبح 30 يوماً إذا أمضى العامل 5 سنوات متصلة في الخدمة              30 يوماً، خمس سنوات                  المادة 24
137  annual_leave  عدد أيام الإجازة السنوية  leave_benefits      نعم                                 خلاف في الرصيد المستحق             تحديد عدد أيام الإجازة السنوية المدفوعة مقدمًا في كل سنة  أيام الإجازة، annual leave days  نموذج عقد العمل – البند 8
144  annual_leave            أنواع الإجازات  leave_benefits      نعم                                           نزاع مستحقات                                        تحديد أنواع الإجازات المستحقة              سنوية، مرضية، طارئة               المواد 33-44

In [ ]:
df.loc[133, "description"] = "استحقاق العامل إجازة سنوية مدفوعة لا تقل عن 21 يوماً وتزيد إلى 30 يوماً بعد خمس سنوات خدمة، مع تنظيم الرصيد والاستفادة منه وفق النظام."

df.loc[144, "field"] = "leave_types"
df.loc[144, "title_ar"] = "أنواع الإجازات"

df = df.drop(index=[134,135,137])

In [66]:
field_name = "basic_salary"

print(df[df["field"] == field_name][[
    "field",
    "title_ar",
    "category",
    "required",
    "risk_if_missing",
    "description",
    "keywords",
    "reference"
]].to_string())

          field            title_ar      category required                        risk_if_missing                                                                       description               keywords                  reference
3  basic_salary       الأجر الأساسي  compensation      نعم  بطلان العقد ومخالفة صريحة لنظام العمل  المبلغ المالي الثابت المتفق عليه مقابل العمل سواء شهرياً أو أسبوعياً دون البدلات  أجر، راتب، ريال سعودي                  المادة 18
4  basic_salary  قيمة الأجر الأساسي  compensation      نعم                  نزاع مباشر على الراتب                             المبلغ الأساسي الذي يبنى عليه الأجر والحقوق ذات الصلة  أجر أساسي، basic wage  نموذج عقد العمل – البند 9

In [ ]:

df.loc[3, "description"] = "المبلغ المالي الثابت المتفق عليه مقابل العمل سواء شهرياً أو أسبوعياً دون البدلات، ويعد أساس احتساب بعض الحقوق النظامية."

df = df.drop(index=[4])

In [68]:
duplicates = df[df.duplicated(subset=["field"], keep=False)]

print("عدد الحقول المكررة:", duplicates["field"].nunique())
print("\nالحقول المكررة:\n")

dup_counts = df["field"].value_counts()
dup_counts = dup_counts[dup_counts > 1]

print(dup_counts)

عدد الحقول المكررة: 37

الحقول المكررة:

field
disciplinary_penalties                5
working_hours_daily                   4
job_duties                            4
contract_written_copy                 4
notice_by_email_or_registered_mail    4
good_conduct_ethics                   4
contract_duration                     3
accommodation_conditions              3
health_care                           3
termination_cases                     3
confidentiality                       3
work_tools_provision                  3
social_insurance                      3
transport_provision                   3
anti_harassment_policy                3
employee_national_address             2
dispute_resolution_clause             2
training_obligation                   2
employer_national_address             2
disciplinary_investigation            2
applicable_law_clause                 2
job_grade                             2
job_title                             2
warning_before_penalty                2
contract_execution_date               2
suspension_from_work                  2
intellectual_property                 2
work_location                         2
wage_payment_method                   2
health_safety_rules                   2
first_aid_provision                   2
housing_allowance                     2
grievance_right                       2
transport_costs                       2
notice_period                         2
contract_data_amendment               2
transport_allowance                   2
Name: count, dtype: int64

سويت فنكشن لتسهيل

In [69]:
def keep_row(field_name, keep_index):
    global df

    rows_before = len(df)

    df = df.drop(
        df[(df["field"] == field_name) & (df.index != keep_index)].index
    )

    rows_after = len(df)

    print(f"تم تنظيف {field_name}")
    print("تم حذف:", rows_before - rows_after, "صف")
def review_field(field_name):
    rows = df[df["field"] == field_name].copy()

    if len(rows) == 0:
        return

    print("=" * 100)
    print("FIELD:", field_name)
    print("عدد الصفوف:", len(rows))
    print("=" * 100)

    cols = [
        "field",
        "title_ar",
        "category",
        "required",
        "risk_if_missing",
        "description",
        "keywords",
        "reference"
    ]

    print(rows[cols].to_string())

In [70]:
review_field("disciplinary_penalties")

====================================================================================================
FIELD: disciplinary_penalties
عدد الصفوف: 5
====================================================================================================
                     field                  title_ar         category required            risk_if_missing                                      description          keywords  reference
75  disciplinary_penalties        الجزاءات التأديبية  employer_rights       لا           تعسف في العقوبات              تحديد المخالفات والعقوبات التأديبية     جزاءات، إنذار  المادة 38
77  disciplinary_penalties        العقوبات التأديبية  employer_rights      نعم                 تعسف إداري                           أنواع العقوبات وحدودها  إنذار، خصم، جزاء  المادة 58
81  disciplinary_penalties  جدول المخالفات والعقوبات  employer_rights       لا  تعسف أو عدم وضوح الجزاءات                  وجود لائحة جزاءات واضحة ومعتمدة    جزاءات، عقوبات  المادة 38
84  disciplinary_penalties        التدرج في العقوبات  employer_rights      نعم                  عدم عدالة                 تصاعد العقوبة حسب تكرار المخالفة    أول مرة، تكرار     ص34-36
89  disciplinary_penalties  جدول المخالفات والجزاءات  employer_rights      نعم        ضعف الإنفاذ الداخلي  قائمة المخالفات والعقوبات المعتمدة داخل اللائحة   مخالفات، جزاءات     ص34-36

In [71]:
df.loc[89, "title_ar"] = "العقوبات والجزاءات التأديبية"
df.loc[89, "description"] = "تشمل الجزاءات التأديبية المعتمدة: الإنذار الكتابي، الحسم من الأجر، الحرمان من مزايا، الإيقاف المؤقت عن العمل، أو الفصل في المخالفات الجسيمة وفق النظام."
df.loc[89, "keywords"] = "جزاءات، عقوبات، مخالفات، إنذار، خصم"
df.loc[89, "reference"] = "المادة 38، المادة 58، ص34-36"

keep_row("disciplinary_penalties", 89)

تم تنظيف disciplinary_penalties
تم حذف: 4 صف

In [72]:
review_field("working_hours_daily")

====================================================================================================
FIELD: working_hours_daily
عدد الصفوف: 4
====================================================================================================
                   field             title_ar       category required                                         risk_if_missing                                                         description                       keywords  reference
266  working_hours_daily          ساعات العمل  work_schedule      نعم           مخالفة الحد الأقصى للنظام وضياع الأجر الإضافي                              تحديد عدد الساعات اليومية أو الأسبوعية               ساعات، دوام، وقت  المادة 23
267  working_hours_daily   تفاصيل أوقات العمل  work_schedule      نعم                                               نزاع دوام                              ساعات العمل والراحة الأسبوعية واليومية                    دوام، ساعات  المادة 26
268  working_hours_daily          ساعات العمل  work_schedule      نعم  تشغيل العامل أكثر من الحد النظامي واستحقاق أجور إضافية  تحديد الساعات اليومية (مثلاً 8 ساعات) أو الأسبوعية (مثلاً 48 ساعة)  ساعات، دوام، يومياً، أسبوعياً  المادة 23
269  working_hours_daily  ساعات العمل اليومية  work_schedule      نعم                                        تشغيل زائد مخالف                                       تحديد عدد ساعات العمل اليومية                    ساعات، دوام  المادة 23

In [73]:
df.loc[268, "title_ar"] = "ساعات العمل"
df.loc[268, "description"] = "تحديد ساعات العمل بما لا يتجاوز الحد النظامي، مثل 8 ساعات يومياً أو 48 ساعة أسبوعياً، مع مراعاة الراحة الأسبوعية وأحكام العمل الإضافي."
df.loc[268, "keywords"] = "ساعات، دوام، يومياً، أسبوعياً، إضافي"
df.loc[268, "reference"] = "المادة 23، المادة 26"

keep_row("working_hours_daily", 268)

تم تنظيف working_hours_daily
تم حذف: 3 صف

In [74]:
review_field("notice_by_email_or_registered_mail")

====================================================================================================
FIELD: notice_by_email_or_registered_mail
عدد الصفوف: 4
====================================================================================================
                                  field                                title_ar            category required      risk_if_missing                                                                   description                  keywords                     reference
110  notice_by_email_or_registered_mail     عدم الاعتداد بالإشعارات غير الموثقة  general_provisions       لا    نزاع في الإشعارات  لا يعتد بالإشعارات أو المراسلات إلا إذا تمت بالوسائل المعتمدة ووفق المتطلبات            إشعار، مراسلات  نموذج عقد العمل – البند 14.1
111  notice_by_email_or_registered_mail  الإشعارات بالبريد الإلكتروني أو المسجل  general_provisions       لا  نزاع في صحة التبليغ                                      طرق تبادل الإشعارات المعتمدة بين الطرفين  بريد إلكتروني، بريد مسجل       المادة الخامسة والعشرون
112  notice_by_email_or_registered_mail                   طريقة تبليغ الإشعارات  general_provisions       لا      نزاع في الإشعار                                                  تحديد وسيلة التبليغ المعتمدة               إشعار، بريد                       general
113  notice_by_email_or_registered_mail     وسيلة بديلة للتبليغ عند تعذر المنصة  general_provisions       لا         تعطل الإشعار            عند عدم توفر الخدمة على المنصة يتم الإشعار بوسائل معترف بها نظامًا                تبليغ بديل  نموذج عقد العمل – البند 14.2

In [75]:
df.loc[111, "title_ar"] = "الإشعارات الرسمية بين الطرفين"
df.loc[111, "description"] = "تتم الإشعارات والمراسلات الرسمية بين الطرفين عبر البريد الإلكتروني المعتمد، البريد المسجل، أو أي وسيلة تبليغ موثقة ومعترف بها نظامًا."
df.loc[111, "keywords"] = "إشعار، بريد إلكتروني، بريد مسجل، تبليغ"
df.loc[111, "reference"] = "المادة الخامسة والعشرون، نموذج عقد العمل – البند 14"

keep_row("notice_by_email_or_registered_mail", 111)

تم تنظيف notice_by_email_or_registered_mail
تم حذف: 3 صف

In [76]:
review_field("contract_written_copy")
review_field("good_conduct_ethics")
review_field("job_duties")
review_field("work_tools_provision")
review_field("social_insurance")
review_field("accommodation_conditions")
review_field("contract_duration")

====================================================================================================
FIELD: contract_written_copy
عدد الصفوف: 4
====================================================================================================
                     field                               title_ar            category required                 risk_if_missing                                                             description                       keywords                      reference
94   contract_written_copy         تحرير العقد بالعربية من نسختين  general_provisions      نعم        خلاف على النسخة المعتمدة                            تحرير العقد باللغة العربية من نسختين أصليتين                العربية، نسختين        المادة السادسة والعشرون
100  contract_written_copy                   نسخة مكتوبة من العقد  general_provisions      نعم  صعوبة إثبات الحقوق والالتزامات                 يجب وجود عقد واضح من نسختين أصليتين وتسليم نسخة لكل طرف  نسخة، عقد مكتوب، نسخة لكل طرف                      المادة 17
102  contract_written_copy                نسخة إلكترونية من العقد  general_provisions      نعم        صعوبة الوصول لنسخة العقد                   يحرر العقد كنسخة إلكترونية متطابقة ويستلم كل طرف نسخة                 نسخة إلكترونية  نموذج عقد العمل – البند 14.10
116  contract_written_copy  توثيق الإشعارات والإجراءات عبر المنصة  general_provisions      نعم                   صعوبة الإثبات  توثيق التنبيهات والمراسلات والإشعارات على المنصة يجعلها قابلة للاحتجاج                    منصة، توثيق   نموذج عقد العمل – البند 14.1
====================================================================================================
FIELD: good_conduct_ethics
عدد الصفوف: 4
====================================================================================================
                  field                    title_ar              category required   risk_if_missing                                            description        keywords                     reference
57  good_conduct_ethics         مخالفات سلوك العامل  employee_obligations      نعم    بيئة عمل سلبية                     إساءة، شجار، اعتداء، سلوك غير مهني   اعتداء، إساءة                        ص35-36
59  good_conduct_ethics         ضوابط سلوكيات العمل  employee_obligations      نعم  نزاعات وسوء سلوك                 قواعد السلوك والانضباط داخل بيئة العمل    سلوك، انضباط                     المادة 53
63  good_conduct_ethics  حسن السلوك وأخلاقيات العمل  employee_obligations      نعم    مساءلة تأديبية  الالتزام بالأنظمة والآداب العامة وقواعد السلوك المهني  سلوك، أخلاقيات  نموذج عقد العمل – البند 12.3
74  good_conduct_ethics         مخالفات تنظيم العمل  employee_obligations      نعم        سوء انضباط      مخالفات السلوك داخل مكان العمل واستخدام الممتلكات     سلوك، تنظيم                           ص34
====================================================================================================
FIELD: job_duties
عدد الصفوف: 4
====================================================================================================
          field              title_ar              category required                                                     risk_if_missing                                                                   description                  keywords                     reference
65   job_duties       المهام الوظيفية  employee_obligations      نعم                                      استغلال العامل بمهام غير واضحة                                             تحديد المسؤوليات والمهام المطلوبة              مهام، duties                     المادة 18
68   job_duties  أداء العمل المكلف به  employee_obligations      نعم                                                        إخلال بالعقد  يلتزم الطرف الثاني بأداء العمل وفق أصول المهنة وتعليمات الطرف الأول النظامية  أداء العمل، instructions  نموذج عقد العمل – البند 12.1
73   job_duties         واجبات العامل  employee_obligations      نعم                                                      مساءلة تأديبية                                           التزامات العامل تجاه العمل والأنظمة            العامل، واجبات                     المادة 48
123  job_duties   موضوع العقد والمهام       job_information      نعم  تكليف العامل بمهام غير مهنته الموثقة أو رفض العامل لمهام غير محددة                 تحديد المسمى الوظيفي وطبيعة العمل والمهام المسندة للعامل بدقة    مهام، وظيفة، مسمى، عمل                     المادة 18
====================================================================================================
FIELD: work_tools_provision
عدد الصفوف: 3
====================================================================================================
                   field                              title_ar              category required        risk_if_missing                                                                 description        keywords                     reference
58  work_tools_provision           المحافظة على الأدوات والعهد  employee_obligations      نعم   تلف أو فقدان ممتلكات  يلتزم العامل بالعناية بالأدوات والمواد المسلمة له وإعادة غير المستعمل منها     عهدة، أدوات  نموذج عقد العمل – البند 12.2
62  work_tools_provision  إساءة استخدام أدوات وممتلكات المنشأة  employee_obligations       لا          خسائر تشغيلية                                     إتلاف أو إساءة استخدام الأجهزة والمعدات  معدات، ممتلكات                           ص34
91  work_tools_provision                     توفير أدوات العمل       employer_rights       لا  ضعف الإنتاجية أو نزاع                                           توفير الأدوات اللازمة لأداء العمل    أدوات، معدات                     المادة 23
====================================================================================================
FIELD: social_insurance
عدد الصفوف: 3
====================================================================================================
                field                              title_ar          category required               risk_if_missing                                                                                         description                 keywords                                  reference
10   social_insurance          استقطاع التأمينات الاجتماعية      compensation      نعم            نزاع في صافي الأجر                            تحديد نسبة أو مقدار الاستقطاع الخاص بالمؤسسة العامة للتأمينات الاجتماعية            GOSI، تأمينات                  نموذج عقد العمل – البند 9
172  social_insurance  تسجيل العامل في التأمينات الاجتماعية  legal_compliance      نعم  مخالفة نظامية ومطالبات لاحقة                             التزام صاحب العمل بتسجيل العامل لدى المؤسسة العامة للتأمينات الاجتماعية           تأمينات، تسجيل               نموذج عقد العمل – البند 11.6
199  social_insurance                  التأمينات الاجتماعية  legal_compliance      نعم  غرامات مالية ومطالبات نظامية  التزام صاحب العمل بتسجيل العامل في المؤسسة العامة للتأمينات الاجتماعية وسداد الاشتراكات حسب النظام  تأمينات، GOSI، اشتراكات  البند رابعاً، رابعاً: التزامات صاحب العمل
====================================================================================================
FIELD: accommodation_conditions
عدد الصفوف: 3
====================================================================================================
                        field                    title_ar        category required      risk_if_missing                           description   keywords  reference
132  accommodation_conditions           شروط السكن المقدم  leave_benefits       لا  نزاع على جودة السكن       تنظيم السكن إذا وفره صاحب العمل  سكن عمالي  المادة 30
155  accommodation_conditions  معايير سكن العمال والخدمات  leave_benefits       لا        مخالفات سكنية  متطلبات سكن أو خدمات للعمالة المقدمة   سكن عمال     ملحق 4
156  accommodation_conditions               السكن العمالي  leave_benefits       لا         نزاعات مزايا              تنظيم توفير السكن إن وجد        سكن  المادة 30
====================================================================================================
FIELD: contract_duration
عدد الصفوف: 3
====================================================================================================
                 field                          title_ar          category required                  risk_if_missing                                                                     description                keywords           reference
35   contract_duration                         مدة العقد    contract_terms      نعم  خلاف حول انتهاء العقد أو تجديده  تحديد مدة العقد وبيان ما إذا كان محدد المدة أو غير محدد، وشروط التجديد إن وجدت  مدة، عقد، نهاية، تجديد           المادة 25
49   contract_duration     الحد الأعلى لمدة العقد المؤقت    contract_terms       لا                      تجديد مخالف               العقد المؤقت لا يتجاوز 3 أشهر ويجدد بما لا يتجاوز 6 أشهر خلال سنة    مؤقت، 3 أشهر، 6 أشهر  نموذج العقد المؤقت
250  contract_duration  انتهاء العقد المؤقت بانتهاء مدته  termination_exit      نعم               خلاف حول الاستمرار                                  ينتهي العقد المؤقت بانتهاء مدته أو مدة التجديد       مؤقت، نهاية المدة  نموذج العقد المؤقت

In [77]:
df.loc[100, "title_ar"] = "نسخة مكتوبة من العقد"
df.loc[100, "description"] = "يجب تحرير عقد العمل من نسختين واضحتين، وتسليم نسخة لكل طرف، ويجوز أن تكون النسخة إلكترونية معتمدة."
df.loc[100, "keywords"] = "نسخة، عقد مكتوب، نسخة إلكترونية"
df.loc[100, "reference"] = "المادة 17، المادة السادسة والعشرون، نموذج عقد العمل – البند 14.10"

keep_row("contract_written_copy", 100)
df.loc[63, "title_ar"] = "حسن السلوك وأخلاقيات العمل"
df.loc[63, "description"] = "يلتزم العامل بالأنظمة والآداب العامة، واحترام قواعد السلوك المهني والانضباط داخل بيئة العمل."
df.loc[63, "keywords"] = "سلوك، أخلاقيات، انضباط، احترام"
df.loc[63, "reference"] = "المادة 53، نموذج عقد العمل – البند 12.3"

keep_row("good_conduct_ethics", 63)

df.loc[123, "title_ar"] = "المهام الوظيفية"
df.loc[123, "category"] = "job_information"
df.loc[123, "description"] = "تحديد المسمى الوظيفي وطبيعة العمل والمهام والمسؤوليات المسندة للعامل بشكل واضح."
df.loc[123, "keywords"] = "مهام، وظيفة، مسؤوليات، مسمى"
df.loc[123, "reference"] = "المادة 18، المادة 48، نموذج عقد العمل – البند 12.1"

keep_row("job_duties", 123)

df.loc[91, "title_ar"] = "توفير أدوات العمل"
df.loc[91, "category"] = "employer_rights"
df.loc[91, "description"] = "يلتزم صاحب العمل بتوفير الأدوات والمعدات اللازمة لأداء العامل مهامه، وعلى العامل المحافظة عليها."
df.loc[91, "keywords"] = "أدوات، معدات، عهدة"
df.loc[91, "reference"] = "المادة 23، نموذج عقد العمل – البند 12.2"

keep_row("work_tools_provision", 91)

df.loc[199, "title_ar"] = "التأمينات الاجتماعية"
df.loc[199, "category"] = "legal_compliance"
df.loc[199, "description"] = "يلتزم صاحب العمل بتسجيل العامل في المؤسسة العامة للتأمينات الاجتماعية وسداد الاشتراكات النظامية."
df.loc[199, "keywords"] = "تأمينات، GOSI، تسجيل، اشتراكات"
df.loc[199, "reference"] = "نظام التأمينات، البند رابعاً، نموذج عقد العمل – البند 11.6"

keep_row("social_insurance", 199)

تم تنظيف contract_written_copy
تم حذف: 3 صف
تم تنظيف good_conduct_ethics
تم حذف: 3 صف
تم تنظيف job_duties
تم حذف: 3 صف
تم تنظيف work_tools_provision
تم حذف: 2 صف
تم تنظيف social_insurance
تم حذف: 2 صف

In [78]:
df.loc[132, "title_ar"] = "شروط السكن المقدم"
df.loc[132, "description"] = "إذا وفر صاحب العمل سكنًا للعامل، فيجب تحديد شروطه ومستواه وصلاحيته للاستخدام."
df.loc[132, "keywords"] = "سكن، سكن عمالي، إقامة"
df.loc[132, "reference"] = "المادة 30"

keep_row("accommodation_conditions", 132)
df.loc[35, "title_ar"] = "مدة العقد"
df.loc[35, "description"] = "تحديد مدة العقد وبيان ما إذا كان محدد المدة أو غير محدد المدة، وشروط التجديد أو الانتهاء."
df.loc[35, "keywords"] = "مدة، عقد، تجديد، نهاية"
df.loc[35, "reference"] = "المادة 25"

keep_row("contract_duration", 35)

تم تنظيف accommodation_conditions
تم حذف: 2 صف
تم تنظيف contract_duration
تم حذف: 2 صف

In [79]:
review_field("health_care")
review_field("termination_cases")
review_field("confidentiality")
review_field("transport_provision")
review_field("anti_harassment_policy")
review_field("dispute_resolution_clause")
review_field("employee_national_address")
review_field("training_obligation")
review_field("wage_payment_method")

====================================================================================================
FIELD: health_care
عدد الصفوف: 3
====================================================================================================
           field                 title_ar          category required                                    risk_if_missing                                                   description                     keywords                                  reference
143  health_care           الرعاية الطبية    leave_benefits      نعم                                      مخالفة نظامية                       التزام المنشأة بالرعاية الطبية للعاملين                    علاج، طبي                                  المادة 49
146  health_care  الرعاية الصحية الوقائية    leave_benefits       لا                               مخالفة التزامات صحية  يلتزم الطرف الأول بتوفير الرعاية الصحية الوقائية وفق الأنظمة                 رعاية وقائية               نموذج عقد العمل – البند 11.5
184  health_care            التأمين الصحي  legal_compliance      نعم  مخالفة نظام الضمان الصحي وتحمل تكاليف علاج الموظف          توفير الرعاية الطبية للعامل وأسرته إن وجد وفق النظام  تأمين طبي، رعاية صحية، علاج  البند رابعاً، رابعاً: التزامات صاحب العمل
====================================================================================================
FIELD: termination_cases
عدد الصفوف: 3
====================================================================================================
                 field                title_ar          category required                      risk_if_missing                                        description              keywords           reference
251  termination_cases  حالات فسخ العقد المؤقت  termination_exit       لا                       نزاع عند الفسخ  حالات الفسخ المحددة مثل الغياب والتزوير والاعتداء              فسخ مؤقت  نموذج العقد المؤقت
252  termination_cases  حالات انتهاء عقد العمل  termination_exit      نعم                           نزاعات فصل               تحديد الحالات النظامية لانتهاء العقد     انتهاء العقد، فصل           المادة 57
253  termination_cases            انتهاء العقد  termination_exit      نعم  غموض آلية الخروج والنزاعات العمالية    تحديد الحالات التي ينتهي فيها الارتباط التعاقدي  انتهاء، فسخ، استقالة        المادة 74/80
====================================================================================================
FIELD: confidentiality
عدد الصفوف: 3
====================================================================================================
              field              title_ar                      category required                   risk_if_missing                                                               description              keywords                                    reference
31  confidentiality                السرية  confidentiality_restrictions       لا               تسريب معلومات العمل                                          الحفاظ على أسرار وبيانات المنشأة                  سرية                                      اختياري
32  confidentiality  خصوصية بيانات الموظف  confidentiality_restrictions       لا                تسريب بيانات شخصية                                               حماية بيانات العامل الشخصية        بيانات، خصوصية                                best practice
60  confidentiality  المحافظة على الأسرار          employee_obligations      نعم  تسريب أسرار المنشأة وضياع حقوقها  التزام العامل بعدم إفشاء أسرار العمل أو بياناته أثناء العقد وبعد انتهائه  أسرار، خصوصية، كتمان  البند رابعاً، رابعاً: التزامات الطرف الثاني
====================================================================================================
FIELD: transport_provision
عدد الصفوف: 3
====================================================================================================
                   field           title_ar        category required   risk_if_missing                      description      keywords  reference
149  transport_provision  شروط النقل المقدم  leave_benefits       لا    نزاع على النقل  تنظيم النقل إذا وفره صاحب العمل    نقل موظفين  المادة 30
150  transport_provision       النقل للعامل  leave_benefits       لا  نزاع مزايا العمل        تنظيم وسيلة النقل إن وجدت  نقل، مواصلات  المادة 30
151  transport_provision     السكن أو النقل  leave_benefits       لا        نزاع مزايا       تنظيم بدل أو توفير سكن/نقل      سكن، نقل  المادة 25
====================================================================================================
FIELD: anti_harassment_policy
عدد الصفوف: 3
====================================================================================================
                      field                    title_ar          category required        risk_if_missing                                description     keywords  reference
158  anti_harassment_policy         حظر الإساءة والتحرش  legal_compliance      نعم    مخاطر قانونية عالية   منع الإساءة اللفظية أو الجسدية أو التحرش  تحرش، إساءة  المادة 54
175  anti_harassment_policy      جزاءات التحرش والإساءة  legal_compliance      نعم  مسؤولية قانونية عالية  عقوبات التحرش أو الإساءة اللفظية والجسدية  تحرش، إساءة     ص35-36
176  anti_harassment_policy  الحماية من الإساءة والتحرش  legal_compliance      نعم      بيئة عمل غير آمنة          حماية العامل من الإساءة أو التحرش  تحرش، إساءة      legal
====================================================================================================
FIELD: dispute_resolution_clause
عدد الصفوف: 2
====================================================================================================
                         field                 title_ar            category required     risk_if_missing                                      description              keywords                reference
101  dispute_resolution_clause         آلية حل النزاعات  general_provisions      نعم      تأخر حل النزاع                 تحديد الجهة المختصة لحل الخلافات           نزاع، تسوية                المادة 40
107  dispute_resolution_clause  اختصاص المحكمة العمالية  general_provisions      نعم  غموض الجهة المختصة  المحكمة العمالية هي المختصة عند تعذر الحل الودي  محكمة عمالية، اختصاص  المادة الحادية والعشرون
====================================================================================================
FIELD: employee_national_address
عدد الصفوف: 2
====================================================================================================
                         field                       title_ar category required         risk_if_missing                                     description              keywords                              reference
215  employee_national_address  العنوان الوطني المختصر للعامل  parties       لا           صعوبة التبليغ             العنوان الوطني المختصر للطرف الثاني            عنوان وطني  نموذج عقد العمل – بيانات الطرف الثاني
220  employee_national_address         العنوان المختار للعامل  parties       لا  صعوبة الإشعار والتواصل  العنوان المعتمد للمراسلات الخاصة بالطرف الثاني  عنوان مختار، مراسلات                            مقدمة العقد
====================================================================================================
FIELD: training_obligation
عدد الصفوف: 2
====================================================================================================
                  field                title_ar              category required     risk_if_missing                    description      keywords  reference
71  training_obligation        التدريب والتأهيل  employee_obligations       لا         ضعف الكفاءة  برامج تدريب الموظفين وتطويرهم  تدريب، تطوير  المادة 13
72  training_obligation  برامج التدريب والتأهيل  employee_obligations       لا  ضعف التطوير المهني    تنظيم التدريب ورفع المهارات  تدريب، تأهيل  المادة 35
====================================================================================================
FIELD: wage_payment_method
عدد الصفوف: 2
====================================================================================================
                  field                        title_ar      category required                    risk_if_missing                                                           description               keywords                   reference
29  wage_payment_method                 طريقة صرف الأجر  compensation      نعم  نزاع في وسيلة السداد وإثبات الدفع  تحديد وسيلة وموعد صرف الرواتب، مثل التحويل البنكي أو أي وسيلة معتمدة  راتب، تحويل، بنك، صرف  المادة 15، نموذج عقد العمل
30  wage_payment_method  الالتزام بالأجور وحقوق العمالة  compensation      نعم                     غرامات ونزاعات                            دفع الأجور والالتزام بحقوق العمالة المقدمة             أجور، حقوق                      ص57-61

In [80]:
df.loc[184, "title_ar"] = "الرعاية الصحية والتأمين الطبي"
df.loc[184, "category"] = "legal_compliance"
df.loc[184, "description"] = "يلتزم صاحب العمل بتوفير الرعاية الصحية والتأمين الطبي للعامل وفق الأنظمة المعمول بها، ولأسرته إذا نص النظام أو العقد على ذلك."
df.loc[184, "keywords"] = "تأمين طبي، علاج، رعاية صحية"
df.loc[184, "reference"] = "المادة 49، البند رابعاً، نموذج عقد العمل – البند 11.5"

keep_row("health_care", 184)

df.loc[252, "title_ar"] = "حالات انتهاء عقد العمل"
df.loc[252, "description"] = "ينتهي عقد العمل في الحالات النظامية مثل: اتفاق الطرفين على الإنهاء، انتهاء مدة العقد المحدد، رغبة أحد الطرفين مع مراعاة الإشعار، بلوغ سن التقاعد، القوة القاهرة، إغلاق المنشأة، الاستقالة المقبولة، أو الفصل المشروع وفق النظام."
df.loc[252, "keywords"] = "انتهاء العقد، فصل، استقالة، فسخ"
df.loc[252, "reference"] = "المادة 57، المادة 74، المادة 80"

keep_row("termination_cases", 252)

df.loc[60, "title_ar"] = "السرية والمحافظة على الأسرار"
df.loc[60, "category"] = "confidentiality_restrictions"
df.loc[60, "description"] = "يلتزم العامل بعدم إفشاء أسرار العمل أو بيانات المنشأة أو البيانات الشخصية التي يطلع عليها أثناء العقد وبعد انتهائه."
df.loc[60, "keywords"] = "سرية، أسرار، خصوصية، بيانات"
df.loc[60, "reference"] = "التزامات العامل، أفضل الممارسات"

keep_row("confidentiality", 60)
df.loc[150, "title_ar"] = "النقل للعامل"
df.loc[150, "description"] = "إذا وفر صاحب العمل وسيلة نقل للعامل أو بدل نقل، فيجب تنظيم ذلك بوضوح في العقد."
df.loc[150, "keywords"] = "نقل، مواصلات، بدل نقل"
df.loc[150, "reference"] = "المادة 30، المادة 25"

keep_row("transport_provision", 150)

تم تنظيف health_care
تم حذف: 2 صف
تم تنظيف termination_cases
تم حذف: 2 صف
تم تنظيف confidentiality
تم حذف: 2 صف
تم تنظيف transport_provision
تم حذف: 2 صف

In [81]:
df.loc[176, "title_ar"] = "الحماية من الإساءة والتحرش"
df.loc[176, "description"] = "يلتزم صاحب العمل بتوفير بيئة عمل آمنة وخالية من الإساءة اللفظية أو الجسدية أو التحرش، مع اتخاذ الإجراءات النظامية عند المخالفة."
df.loc[176, "keywords"] = "تحرش، إساءة، بيئة آمنة"
df.loc[176, "reference"] = "المادة 54، ص35-36"

keep_row("anti_harassment_policy", 176)

df.loc[107, "title_ar"] = "حل النزاعات والاختصاص القضائي"
df.loc[107, "description"] = "تتم محاولة حل النزاع وديًا أولاً، وعند التعذر تكون المحكمة العمالية هي الجهة المختصة."
df.loc[107, "keywords"] = "نزاع، محكمة عمالية، تسوية"
df.loc[107, "reference"] = "المادة 40، المادة الحادية والعشرون"

keep_row("dispute_resolution_clause", 107)


df.loc[215, "title_ar"] = "العنوان الوطني للعامل"
df.loc[215, "description"] = "العنوان الوطني أو عنوان المراسلات المعتمد الخاص بالعامل."
df.loc[215, "keywords"] = "عنوان وطني، مراسلات"
df.loc[215, "reference"] = "نموذج عقد العمل"

keep_row("employee_national_address", 215)

df.loc[72, "title_ar"] = "التدريب والتأهيل"
df.loc[72, "description"] = "تنظيم برامج التدريب والتأهيل ورفع مهارات العامل بما يخدم طبيعة العمل."
df.loc[72, "keywords"] = "تدريب، تأهيل، تطوير"
df.loc[72, "reference"] = "المادة 13، المادة 35"

keep_row("training_obligation", 72)


df.loc[29, "title_ar"] = "طريقة صرف الأجر"
df.loc[29, "description"] = "تحديد وسيلة وموعد صرف الأجر، مثل التحويل البنكي أو أي وسيلة دفع معتمدة نظامًا."
df.loc[29, "keywords"] = "راتب، تحويل، بنك، صرف"
df.loc[29, "reference"] = "المادة 15، نموذج عقد العمل"

keep_row("wage_payment_method", 29)

تم تنظيف anti_harassment_policy
تم حذف: 2 صف
تم تنظيف dispute_resolution_clause
تم حذف: 1 صف
تم تنظيف employee_national_address
تم حذف: 1 صف
تم تنظيف training_obligation
تم حذف: 1 صف
تم تنظيف wage_payment_method
تم حذف: 1 صف

In [82]:
review_field("disciplinary_investigation")
review_field("employer_national_address")
review_field("contract_data_amendment")
review_field("applicable_law_clause")
review_field("job_grade")
review_field("job_title")
review_field("contract_execution_date")
review_field("suspension_from_work")
review_field("intellectual_property")

====================================================================================================
FIELD: disciplinary_investigation
عدد الصفوف: 2
====================================================================================================
                         field                 title_ar         category required       risk_if_missing                                                      description            keywords  reference
76  disciplinary_investigation      التحقيق قبل العقوبة  employer_rights      نعم  فرض عقوبات غير عادلة  وجوب التحقيق قبل توقيع العقوبة أو فرض الجزاء في الحالات اللازمة  تحقيق، عقوبة، جزاء  المادة 38
80  disciplinary_investigation  إجراءات التحقيق الداخلي  employer_rights      نعم      عقوبات غير عادلة                               تنظيم التحقيق مع العامل قبل الجزاء       تحقيق، مخالفة  المادة 56
====================================================================================================
FIELD: employer_national_address
عدد الصفوف: 2
====================================================================================================
                         field                        title_ar category required           risk_if_missing                                    description              keywords                             reference
225  employer_national_address  العنوان الوطني المختصر للمنشأة  parties       لا  صعوبة التبليغ والمراسلات             العنوان الوطني المعتمد للطرف الأول            عنوان وطني  نموذج عقد العمل – بيانات الطرف الأول
230  employer_national_address     العنوان المختار لصاحب العمل  parties       لا  صعوبة التبليغ والإشعارات  العنوان المعتمد للمراسلات الخاصة بالطرف الأول  عنوان مختار، مراسلات                           مقدمة العقد
====================================================================================================
FIELD: contract_data_amendment
عدد الصفوف: 2
====================================================================================================
                      field                            title_ar            category required       risk_if_missing                                                      description      keywords                     reference
93  contract_data_amendment          توثيق التعديلات عبر المنصة  general_provisions       لا  نزاع حول صحة التعديل                     يلتزم الطرف الأول بتوثيق أي تعديل عبر المنصة   توثيق تعديل  نموذج عقد العمل – البند 14.9
95  contract_data_amendment  تعديل بيانات العقد بموافقة الطرفين  general_provisions       لا       تعديل غير مشروع  يجوز تعديل بعض البيانات بموافقة الطرفين ووفق الضوابط والإجراءات  تعديل بيانات  نموذج عقد العمل – البند 14.8
====================================================================================================
FIELD: applicable_law_clause
عدد الصفوف: 2
====================================================================================================
                     field                   title_ar            category required risk_if_missing                                                          description         keywords                   reference
118  applicable_law_clause  خضوع العقد للنظام السعودي  general_provisions      نعم     نزاع قانوني                              النظام السعودي هو النظام الواجب التطبيق   النظام السعودي     المادة الحادية والعشرون
159  applicable_law_clause      النظام الواجب التطبيق    legal_compliance      نعم     خلاف قانوني  يخضع العقد لنظام العمل ولوائحه والقرارات واللوائح الداخلية المعتمدة  نظام العمل، law  نموذج عقد العمل – البند 13
====================================================================================================
FIELD: job_grade
عدد الصفوف: 2
====================================================================================================
         field                   title_ar         category required        risk_if_missing                           description           keywords       reference
124  job_grade               درجة الوظيفة  job_information       لا  غموض المرتبة الوظيفية  تحديد الدرجة الوظيفية المتعاقد عليها        درجة، grade  المادة الثالثة
126  job_grade  المرتبة / الفئة / المستوى  job_information       لا     غموض السلم الوظيفي     تحديد المرتبة أو الفئة أو المستوى  مرتبة، مستوى، فئة  المادة الثالثة
====================================================================================================
FIELD: job_title
عدد الصفوف: 2
====================================================================================================
         field        title_ar         category required             risk_if_missing                    description     keywords       reference
125  job_title     رقم الوظيفة  job_information       لا   صعوبة ربط الوظيفة بالهيكل          الرقم الإداري للوظيفة  رقم الوظيفة  المادة الثالثة
127  job_title  المسمى الوظيفي  job_information      نعم  تكليف بمهام غير متفق عليها  تحديد الوظيفة الأساسية للعامل  وظيفة، مسمى       المادة 18
====================================================================================================
FIELD: contract_execution_date
عدد الصفوف: 2
====================================================================================================
                      field            title_ar            category required                    risk_if_missing                                 description             keywords                               reference
37  contract_execution_date  تاريخ مباشرة العمل      contract_terms      نعم  نزاع حول بداية الاستحقاقات والمدة                تحديد تاريخ بدء العمل الفعلي  بداية العمل، مباشرة             المادة 18 / نموذج عقد العمل
96  contract_execution_date   تاريخ إبرام العقد  general_provisions      نعم            نزاع حول بدء الالتزامات  تحديد تاريخ توقيع وإبرام العقد بين الطرفين  إبرام، توقيع، تاريخ  نموذج عقد العمل – البند 1، نموذج العقد
====================================================================================================
FIELD: suspension_from_work
عدد الصفوف: 2
====================================================================================================
                   field                 title_ar         category required risk_if_missing                           description      keywords       reference
85  suspension_from_work  الإيقاف المؤقت عن العمل  employer_rights       لا      نزاع إداري  إيقاف العامل مؤقتًا وفق ضوابط نظامية  إيقاف، تعليق       المادة 66
86  suspension_from_work   الإيقاف عن العمل كجزاء  employer_rights       لا       طعن إداري        إيقاف مؤقت وفق اللائحة والنظام         إيقاف  جداول الجزاءات
====================================================================================================
FIELD: intellectual_property
عدد الصفوف: 2
====================================================================================================
                    field         title_ar                      category required                           risk_if_missing                                                 description               keywords                          reference
33  intellectual_property  الملكية الفكرية  confidentiality_restrictions       لا         نزاع على الحقوق المعنوية والمالية  تنظيم ملكية المخرجات والأعمال والابتكارات الناتجة عن العمل            ملكية فكرية  نموذج عقد العمل – الشروط الإضافية
64  intellectual_property  الملكية الفكرية          employee_obligations  اختياري  ضياع حقوق الابتكارات المنتجة أثناء العمل              ملكية الاختراعات والأعمال التي تمت لصالح العمل  ابتكار، اختراع، ملكية                    التزامات العامل

In [83]:
df.loc[76, "title_ar"] = "التحقيق قبل العقوبة"
df.loc[76, "description"] = "يجب التحقيق مع العامل وسماع أقواله قبل توقيع أي عقوبة تأديبية في الحالات التي تستوجب ذلك، وفق الإجراءات النظامية."
df.loc[76, "keywords"] = "تحقيق، جزاء، عقوبة"
df.loc[76, "reference"] = "المادة 38، المادة 56"

keep_row("disciplinary_investigation", 76)
df.loc[225, "title_ar"] = "العنوان الوطني للمنشأة"
df.loc[225, "description"] = "العنوان الوطني أو عنوان المراسلات المعتمد الخاص بصاحب العمل أو المنشأة."
df.loc[225, "keywords"] = "عنوان وطني، منشأة، مراسلات"
df.loc[225, "reference"] = "نموذج عقد العمل"

keep_row("employer_national_address", 225)

df.loc[95, "title_ar"] = "تعديل بيانات العقد"
df.loc[95, "description"] = "لا يجوز تعديل بيانات أو شروط العقد إلا بموافقة الطرفين، مع توثيق التعديل عبر الوسائل المعتمدة عند اللزوم."
df.loc[95, "keywords"] = "تعديل عقد، موافقة، توثيق"
df.loc[95, "reference"] = "نموذج عقد العمل – البند 14.8، 14.9"

keep_row("contract_data_amendment", 95)

df.loc[159, "title_ar"] = "النظام الواجب التطبيق"
df.loc[159, "description"] = "يخضع عقد العمل لنظام العمل السعودي ولوائحه التنفيذية والأنظمة والقرارات ذات العلاقة."
df.loc[159, "keywords"] = "نظام العمل، السعودية، قانون"
df.loc[159, "reference"] = "المادة الحادية والعشرون، نموذج عقد العمل – البند 13"

keep_row("applicable_law_clause", 159)

df.loc[126, "title_ar"] = "الدرجة أو المستوى الوظيفي"
df.loc[126, "description"] = "تحديد الدرجة أو المرتبة أو المستوى الوظيفي المتفق عليه ضمن الهيكل التنظيمي."
df.loc[126, "keywords"] = "درجة، مستوى، مرتبة"
df.loc[126, "reference"] = "المادة الثالثة"

keep_row("job_grade", 126)



df.loc[127, "title_ar"] = "المسمى الوظيفي"
df.loc[127, "description"] = "تحديد الوظيفة الأساسية أو المسمى الوظيفي الذي يشغله العامل."
df.loc[127, "keywords"] = "وظيفة، مسمى"
df.loc[127, "reference"] = "المادة 18"

keep_row("job_title", 127)

تم تنظيف disciplinary_investigation
تم حذف: 1 صف
تم تنظيف employer_national_address
تم حذف: 1 صف
تم تنظيف contract_data_amendment
تم حذف: 1 صف
تم تنظيف applicable_law_clause
تم حذف: 1 صف
تم تنظيف job_grade
تم حذف: 1 صف
تم تنظيف job_title
تم حذف: 1 صف

In [ ]:
df.loc[96, "field"] = "contract_execution_date"
df.loc[96, "title_ar"] = "تاريخ إبرام العقد"
df.loc[96, "category"] = "general_provisions"
df.loc[96, "description"] = "تاريخ توقيع وإبرام عقد العمل بين الطرفين."
df.loc[96, "keywords"] = "توقيع، إبرام، تاريخ العقد"
df.loc[96, "reference"] = "نموذج عقد العمل – البند 1"

df.loc[37, "field"] = "contract_start_date"
df.loc[37, "title_ar"] = "تاريخ مباشرة العمل"
df.loc[37, "category"] = "contract_terms"
df.loc[37, "description"] = "تاريخ بدء العامل بمباشرة العمل فعليًا وبدء احتساب المدة والحقوق."
df.loc[37, "keywords"] = "بداية العمل، مباشرة، أول يوم"
df.loc[37, "reference"] = "المادة 18، نموذج عقد العمل"
keep_row("contract_execution_date", 96)
keep_row("contract_start_date", 37)


df.loc[85, "title_ar"] = "الإيقاف المؤقت عن العمل"
df.loc[85, "description"] = "يجوز إيقاف العامل مؤقتًا عن العمل كجزاء تأديبي عند ارتكابه مخالفة وظيفية تستوجب ذلك وفق لائحة الجزاءات المعتمدة، على أن يكون ذلك ضمن الجزاءات النظامية وبعد استيفاء الإجراءات التأديبية المقررة مثل التحقيق وسماع أقوال العامل، وبما لا يتجاوز الحدود النظامية."
df.loc[85, "keywords"] = "إيقاف، تعليق، مؤقت"
df.loc[85, "reference"] = "المادة 66"

keep_row("suspension_from_work", 85)


df.loc[33, "title_ar"] = "الملكية الفكرية"
df.loc[33, "category"] = "confidentiality_restrictions"
df.loc[33, "description"] = "تنظيم ملكية الأعمال والمخرجات والابتكارات والحقوق الفكرية الناتجة عن العمل أو المرتبطة به."
df.loc[33, "keywords"] = "ملكية فكرية، ابتكار، اختراع"
df.loc[33, "reference"] = "الشروط الإضافية، أفضل ممارسة"

keep_row("intellectual_property", 33)

تم تنظيف contract_execution_date
تم حذف: 0 صف
تم تنظيف contract_start_date
تم حذف: 0 صف
تم تنظيف suspension_from_work
تم حذف: 1 صف
تم تنظيف intellectual_property
تم حذف: 1 صف

In [85]:

review_field("work_location")
review_field("warning_before_penalty")
review_field("housing_allowance")
review_field("transport_allowance")
review_field("grievance_right")
review_field("transport_costs")
review_field("notice_period")
review_field("health_safety_rules")
review_field("first_aid_provision")

====================================================================================================
FIELD: work_location
عدد الصفوف: 2
====================================================================================================
             field    title_ar         category required                        risk_if_missing                                                            description                      keywords  reference
129  work_location  مكان العمل  job_information      نعم            نقل تعسفي أو خلافات تشغيلية                                                تحديد مقر العمل الأساسي               موقع، مقر العمل  المادة 18
131  work_location  مكان العمل  job_information      نعم  النزاع حول مقر العمل أو النقل التعسفي  تحديد المقر أو المدينة أو الموقع الجغرافي الذي سيؤدي فيه العامل مهامه  مكان العمل، مدينة، موقع، مقر  المادة 18
====================================================================================================
FIELD: warning_before_penalty
عدد الصفوف: 2
====================================================================================================
                     field             title_ar         category required risk_if_missing                   description      keywords       reference
90  warning_before_penalty  الإنذار قبل العقوبة  employer_rights       لا   ضعف الإجراءات  توجيه إنذار قبل بعض الجزاءات  إنذار، تأديب    المواد 58-61
92  warning_before_penalty      الإنذار الكتابي  employer_rights      نعم     ضعف التوثيق  أول درجات الجزاءات التأديبية   إنذار كتابي  جداول الجزاءات
====================================================================================================
FIELD: housing_allowance
عدد الصفوف: 2
====================================================================================================
                field                title_ar      category required   risk_if_missing                            description        keywords                  reference
11  housing_allowance               بدل السكن  compensation       لا  نزاع على المزايا  تحديد بدل السكن إذا اتفق الطرفان عليه         بدل سكن  نموذج عقد العمل – البند 9
12  housing_allowance  بدل السكن لغير السعودي  compensation       لا          نزاع بدل          بدل سكن سنوي أو سكن مؤثث بديل  سكن، غير سعودي          نموذج غير السعودي
====================================================================================================
FIELD: transport_allowance
عدد الصفوف: 2
====================================================================================================
                  field                title_ar      category required   risk_if_missing                             description        keywords                  reference
25  transport_allowance               بدل النقل  compensation       لا  نزاع على البدلات  تحديد بدل النقل إذا اتفق عليه في العقد         بدل نقل  نموذج عقد العمل – البند 9
26  transport_allowance  بدل النقل لغير السعودي  compensation       لا          نزاع بدل         بدل نقل شهري أو توفير وسيلة نقل  نقل، غير سعودي          نموذج غير السعودي
====================================================================================================
FIELD: grievance_right
عدد الصفوف: 2
====================================================================================================
               field                  title_ar          category required                            risk_if_missing                                  description      keywords  reference
173  grievance_right  مدة الاعتراض على العقوبة  legal_compliance       لا                         ضياع فرصة الاعتراض             تحديد مهلة تظلم العامل من الجزاء  اعتراض، مهلة  المادة 71
174  grievance_right       حق التظلم والاعتراض  legal_compliance      نعم  انتقاص حقوق العامل وضعف الحماية الإجرائية  تمكين العامل من التظلم والاعتراض على الجزاء  اعتراض، تظلم  المادة 39
====================================================================================================
FIELD: transport_costs
عدد الصفوف: 2
====================================================================================================
               field       title_ar          category required                                risk_if_missing                                                description               keywords                    reference
255  transport_costs  تكاليف العودة  termination_exit      نعم        تحمل المنشأة غرامات ترحيل أو تذاكر عودة                    تحمل صاحب العمل تذكرة عودة العامل لبلده       عودة، تذكرة، وطن                 البند رابعاً
256  transport_costs   تكلفة العودة  termination_exit      نعم  تحمل المنشأة غرامات ترحيل أو تذاكر عودة قسرية  تحمل صاحب العمل تكاليف عودة العامل لبلده بعد انتهاء العقد  تذكرة عودة، عودة، سفر  رابعاً: التزامات صاحب العمل
====================================================================================================
FIELD: notice_period
عدد الصفوف: 2
====================================================================================================
             field             title_ar          category required                   risk_if_missing                                                                  description                        keywords    reference
248  notice_period         مهلة الإشعار  termination_exit      نعم  إنهاء مفاجئ يترتب عليه دفع تعويض  المدة اللازمة لإخطار الطرف الآخر برغبة إنهاء العقد، مثل 60 يوماً وفق النظام  إشعار، إنهاء، مهلة، ستون يوماً    المادة 75
254  notice_period  الإشعار قبل الإنهاء  termination_exit      نعم                       إنهاء مفاجئ                                          تحديد مدة الإشعار قبل إنهاء العلاقة                    إشعار، إنهاء  termination
====================================================================================================
FIELD: health_safety_rules
عدد الصفوف: 2
====================================================================================================
                   field                title_ar          category required                         risk_if_missing                                                                    description                    keywords                                    reference
178  health_safety_rules  السلامة والصحة المهنية  legal_compliance      نعم                       إصابات ومخاطر عمل                                                      الالتزام بمتطلبات السلامة            سلامة، صحة مهنية                                 المواد 28-32
197  health_safety_rules         تعليمات السلامة  legal_compliance      نعم  وقوع إصابات عمل ومسؤولية قانونية كاملة  الالتزام بقواعد السلامة المهنية واستخدام أدوات الوقاية ومتطلبات الصحة المهنية  سلامة، وقاية، مخاطر، أخطار  البند رابعاً، رابعاً: التزامات الطرف الثاني
====================================================================================================
FIELD: first_aid_provision
عدد الصفوف: 2
====================================================================================================
                   field                 title_ar          category required       risk_if_missing                      description        keywords  reference
169  first_aid_provision  حقيبة الإسعافات الأولية  legal_compliance      نعم          مخالفة سلامة  توفير أدوات إسعاف في موقع العمل  إسعافات، سلامة  المادة 29
170  first_aid_provision      توفير إسعافات أولية  legal_compliance      نعم  مخالفة وسلامة منخفضة      توفير أدوات الإسعاف بالموقع      إسعاف أولي  المادة 29

In [ ]:
df.loc[131, "title_ar"] = "مكان العمل"
df.loc[131, "description"] = "تحديد مقر العمل الأساسي أو المدينة أو الموقع الجغرافي الذي يؤدي فيه العامل مهامه، ولا يجوز نقله بما يخالف النظام أو العقد."
df.loc[131, "keywords"] = "مكان العمل، مقر، مدينة، موقع"
df.loc[131, "reference"] = "المادة 18"
keep_row("work_location", 131)



df.loc[92, "title_ar"] = "الإنذار الكتابي"
df.loc[92, "description"] = "يعد الإنذار الكتابي من الجزاءات التأديبية الأولية، ويستخدم عند بعض المخالفات قبل توقيع جزاءات أشد بحسب جسامة المخالفة وتكرارها."
df.loc[92, "keywords"] = "إنذار، كتابي، جزاء"
df.loc[92, "reference"] = "المواد 58-61، جداول الجزاءات"
keep_row("warning_before_penalty", 92)



df.loc[11, "title_ar"] = "بدل السكن"
df.loc[11, "description"] = "إذا اتفق الطرفان على بدل سكن أو توفير سكن، فيجب تحديد قيمته أو نوع السكن وشروطه بوضوح في العقد."
df.loc[11, "keywords"] = "بدل سكن، سكن"
df.loc[11, "reference"] = "نموذج عقد العمل – البند 9"
keep_row("housing_allowance", 11)



df.loc[25, "title_ar"] = "بدل النقل"
df.loc[25, "description"] = "إذا اتفق الطرفان على بدل نقل أو توفير وسيلة نقل، فيجب تحديد ذلك بوضوح في العقد."
df.loc[25, "keywords"] = "بدل نقل، مواصلات"
df.loc[25, "reference"] = "نموذج عقد العمل – البند 9"
keep_row("transport_allowance", 25)



df.loc[174, "title_ar"] = "حق التظلم والاعتراض"
df.loc[174, "description"] = "للعامل حق التظلم والاعتراض على الجزاءات أو القرارات التي تمسه، خلال المدد والإجراءات النظامية المقررة."
df.loc[174, "keywords"] = "اعتراض، تظلم، شكوى"
df.loc[174, "reference"] = "المادة 39، المادة 71"
keep_row("grievance_right", 174)



df.loc[256, "title_ar"] = "تكاليف عودة العامل"
df.loc[256, "description"] = "يلتزم صاحب العمل بتحمل تكاليف عودة العامل إلى بلده بعد انتهاء العلاقة التعاقدية في الحالات التي يقررها النظام."
df.loc[256, "keywords"] = "عودة، تذكرة، سفر"
df.loc[256, "reference"] = "التزامات صاحب العمل"
keep_row("transport_costs", 256)



df.loc[248, "title_ar"] = "مهلة الإشعار"
df.loc[248, "description"] = "يجب إشعار الطرف الآخر قبل إنهاء العقد غير المحدد المدة خلال المهلة النظامية، ما لم يوجد سبب مشروع للإعفاء من الإشعار."
df.loc[248, "keywords"] = "إشعار، إنهاء، مهلة"
df.loc[248, "reference"] = "المادة 75"
keep_row("notice_period", 248)



df.loc[197, "title_ar"] = "السلامة والصحة المهنية"
df.loc[197, "description"] = "يلتزم صاحب العمل والعامل بتطبيق قواعد السلامة والصحة المهنية، واستخدام أدوات الوقاية، والحد من مخاطر وإصابات العمل."
df.loc[197, "keywords"] = "سلامة، وقاية، إصابات، صحة مهنية"
df.loc[197, "reference"] = "المواد 28-32"
keep_row("health_safety_rules", 197)


df.loc[170, "title_ar"] = "توفير الإسعافات الأولية"
df.loc[170, "description"] = "يلتزم صاحب العمل بتوفير أدوات ومستلزمات الإسعافات الأولية المناسبة في موقع العمل وفق متطلبات السلامة."
df.loc[170, "keywords"] = "إسعافات أولية، سلامة"
df.loc[170, "reference"] = "المادة 29"
keep_row("first_aid_provision", 170)

تم تنظيف work_location
تم حذف: 1 صف
تم تنظيف warning_before_penalty
تم حذف: 1 صف
تم تنظيف housing_allowance
تم حذف: 1 صف
تم تنظيف transport_allowance
تم حذف: 1 صف
تم تنظيف grievance_right
تم حذف: 1 صف
تم تنظيف transport_costs
تم حذف: 1 صف
تم تنظيف notice_period
تم حذف: 1 صف
تم تنظيف health_safety_rules
تم حذف: 1 صف
تم تنظيف first_aid_provision
تم حذف: 1 صف

In [ ]:
df.loc[131, "title_ar"] = "مكان العمل"
df.loc[131, "description"] = "تحديد مقر العمل أو المدينة أو الموقع الجغرافي الذي يؤدي فيه العامل مهامه، ولا يجوز نقل العامل إلى مكان يتطلب تغيير محل إقامته إلا وفق الضوابط النظامية وبموافقته الكتابية عند اللزوم."
df.loc[131, "keywords"] = "مكان العمل، مقر، مدينة، موقع"
df.loc[131, "reference"] = "المادة 18، المادة 58"
keep_row("work_location", 131)


df.loc[92, "title_ar"] = "الإنذار الكتابي"
df.loc[92, "description"] = "الإنذار الكتابي أحد الجزاءات التأديبية المعتمدة، ويستخدم للمخالفات التي تستوجب التنبيه الرسمي قبل اللجوء إلى جزاءات أشد بحسب جسامة المخالفة وتكرارها ووفق لائحة تنظيم العمل."
df.loc[92, "keywords"] = "إنذار، كتابي، جزاء"
df.loc[92, "reference"] = "المواد 66-69، لائحة تنظيم العمل"
keep_row("warning_before_penalty", 92)


df.loc[11, "title_ar"] = "بدل السكن"
df.loc[11, "description"] = "إذا اتفق الطرفان على بدل سكن أو توفير سكن، فيجب النص عليه بوضوح في العقد مع بيان قيمته أو نوع السكن وشروطه."
df.loc[11, "keywords"] = "بدل سكن، سكن"
df.loc[11, "reference"] = "نموذج عقد العمل – البند 9"
keep_row("housing_allowance", 11)


df.loc[25, "title_ar"] = "بدل النقل"
df.loc[25, "description"] = "إذا اتفق الطرفان على بدل نقل أو توفير وسيلة نقل، فيجب تحديد ذلك بوضوح في العقد مع بيان قيمته أو صورته."
df.loc[25, "keywords"] = "بدل نقل، مواصلات"
df.loc[25, "reference"] = "نموذج عقد العمل – البند 9"
keep_row("transport_allowance", 25)


df.loc[174, "title_ar"] = "حق التظلم والاعتراض"
df.loc[174, "description"] = "للعامل حق التظلم والاعتراض على الجزاء التأديبي وفق الإجراءات والمدد النظامية، ويجب تمكينه من ممارسة هذا الحق دون انتقاص."
df.loc[174, "keywords"] = "اعتراض، تظلم، جزاء"
df.loc[174, "reference"] = "المادة 71"
keep_row("grievance_right", 174)


df.loc[256, "title_ar"] = "تكاليف عودة العامل"
df.loc[256, "description"] = "يلتزم صاحب العمل بتحمل تكاليف عودة العامل غير السعودي إلى بلده عند انتهاء العلاقة التعاقدية في الحالات التي يقررها النظام، ما لم يكن سبب عدم العودة راجعًا إلى العامل أو اتفق على غير ذلك في الحدود النظامية."
df.loc[256, "keywords"] = "عودة، تذكرة، سفر"
df.loc[256, "reference"] = "التزامات صاحب العمل"
keep_row("transport_costs", 256)


df.loc[248, "title_ar"] = "مهلة الإشعار"
df.loc[248, "description"] = "في العقد غير المحدد المدة، يجب أن يكون الإنهاء بسبب مشروع مع إشعار مكتوب للطرف الآخر قبل الإنهاء بمدة لا تقل عن 60 يومًا إذا كان أجر العامل يدفع شهريًا، ولا تقل عن 30 يومًا بالنسبة إلى غيره، ما لم يتفق الطرفان على مدة أطول."
df.loc[248, "keywords"] = "إشعار، إنهاء، 60 يوم، 30 يوم"
df.loc[248, "reference"] = "المادة 75"
keep_row("notice_period", 248)


df.loc[197, "title_ar"] = "السلامة والصحة المهنية"
df.loc[197, "description"] = "يلتزم صاحب العمل والعامل بقواعد السلامة والصحة المهنية، واستخدام أدوات الوقاية، والالتزام بالتعليمات اللازمة للحد من مخاطر وإصابات العمل."
df.loc[197, "keywords"] = "سلامة، وقاية، إصابات، صحة مهنية"
df.loc[197, "reference"] = "المواد 121 وما بعدها، والمواد ذات الصلة بالسلامة"
keep_row("health_safety_rules", 197)


df.loc[170, "title_ar"] = "توفير الإسعافات الأولية"
df.loc[170, "description"] = "يلتزم صاحب العمل بتوفير أدوات ومستلزمات الإسعافات الأولية المناسبة في موقع العمل وفق متطلبات السلامة والصحة المهنية."
df.loc[170, "keywords"] = "إسعافات أولية، سلامة"
df.loc[170, "reference"] = "متطلبات السلامة والصحة المهنية"
keep_row("first_aid_provision", 170)

تم تنظيف work_location
تم حذف: 0 صف
تم تنظيف warning_before_penalty
تم حذف: 0 صف
تم تنظيف housing_allowance
تم حذف: 0 صف
تم تنظيف transport_allowance
تم حذف: 0 صف
تم تنظيف grievance_right
تم حذف: 0 صف
تم تنظيف transport_costs
تم حذف: 0 صف
تم تنظيف notice_period
تم حذف: 0 صف
تم تنظيف health_safety_rules
تم حذف: 0 صف
تم تنظيف first_aid_provision
تم حذف: 0 صف

In [88]:

new_rows = [
    {
        "field": "paternity_leave",
        "title_ar": "إجازة الأبوة",
        "category": "leave_benefits",
        "required": "نعم",
        "risk_if_missing": "حرمان العامل من حق نظامي",
        "description": "إجازة مدفوعة الأجر للأب عند ولادة مولود وفق المدة المقررة نظامًا.",
        "keywords": "أبوة، مولود، إجازة",
        "reference": "المادة 113"
    },
    {
        "field": "hajj_leave",
        "title_ar": "إجازة الحج",
        "category": "leave_benefits",
        "required": "لا",
        "risk_if_missing": "نزاع في الاستحقاق",
        "description": "إجازة لأداء فريضة الحج تمنح وفق الشروط النظامية ولمرة واحدة طوال مدة الخدمة.",
        "keywords": "حج، إجازة",
        "reference": "المادة 114"
    },
    {
        "field": "wage_protection_system",
        "title_ar": "نظام حماية الأجور",
        "category": "compensation",
        "required": "نعم",
        "risk_if_missing": "غرامات أو إيقاف خدمات",
        "description": "الالتزام برفع بيانات الأجور وصرف الرواتب عبر الأنظمة والمنصات المعتمدة.",
        "keywords": "WPS، حماية الأجور، مدد",
        "reference": "وزارة الموارد البشرية"
    },
    {
        "field": "ramadan_working_hours",
        "title_ar": "ساعات العمل في رمضان",
        "category": "work_schedule",
        "required": "لا",
        "risk_if_missing": "مخالفة ساعات العمل الموسمية",
        "description": "تخفيض ساعات العمل اليومية خلال شهر رمضان للفئات المشمولة وفق النظام.",
        "keywords": "رمضان، ساعات عمل",
        "reference": "نظام العمل"
    },
    {
        "field": "flexible_work_arrangement",
        "title_ar": "ترتيبات العمل المرن",
        "category": "contract_terms",
        "required": "لا",
        "risk_if_missing": "نزاع على نمط العمل",
        "description": "تنظيم العمل المرن أو الجزئي أو الساعات المرنة وفق الاتفاق واللوائح المعتمدة.",
        "keywords": "مرن، flexible، جزئي",
        "reference": "تنظيم الموارد البشرية"
    }
]

new_df = pd.DataFrame(new_rows)

In [ ]:
import pandas as pd

new_rows = [
{
"field":"digital_contract_documentation",
"title_ar":"التوثيق الرقمي للعقد عبر منصة قوى",
"category":"legal_compliance",
"required":True,
"risk_if_missing":"high",
"description":"يجب توثيق عقد العمل عبر منصة قوى ليكون معتمدًا قانونيًا.",
"keywords":"توثيق العقد; منصة قوى; عقد رقمي; qiwa contract",
"reference":"نظام العمل - منصة قوى"
},

{
"field":"probation_max_duration",
"title_ar":"الحد الأعلى لفترة التجربة",
"category":"contract_terms",
"required":False,
"risk_if_missing":"medium",
"description":"لا يجوز أن تتجاوز فترة التجربة 180 يومًا.",
"keywords":"فترة التجربة; probation period; 180 days",
"reference":"المادة 53"
},

{
"field":"maternity_leave_duration",
"title_ar":"مدة إجازة الوضع",
"category":"leave_benefits",
"required":False,
"risk_if_missing":"low",
"description":"إجازة الأمومة 12 أسبوعًا.",
"keywords":"إجازة وضع; maternity leave",
"reference":"المادة 151"
},

{
"field":"sibling_death_leave",
"title_ar":"إجازة وفاة الأخ أو الأخت",
"category":"leave_benefits",
"required":False,
"risk_if_missing":"low",
"description":"إجازة مدفوعة 3 أيام عند وفاة الأخ أو الأخت.",
"keywords":"وفاة الأخ; وفاة الأخت; bereavement leave",
"reference":"المادة 113"
},

{
"field":"resignation_notice_employee",
"title_ar":"إشعار الاستقالة للعامل",
"category":"termination_exit",
"required":True,
"risk_if_missing":"high",
"description":"يجب إشعار صاحب العمل قبل 30 يومًا.",
"keywords":"إشعار الاستقالة; resignation notice",
"reference":"المادة 75"
},

{
"field":"termination_notice_employer",
"title_ar":"إشعار إنهاء العقد من صاحب العمل",
"category":"termination_exit",
"required":True,
"risk_if_missing":"high",
"description":"يجب إشعار العامل قبل 60 يومًا.",
"keywords":"إشعار إنهاء العقد; termination notice",
"reference":"المادة 75"
},

{
"field":"housing_transport_allowance",
"title_ar":"بدل السكن والنقل",
"category":"compensation",
"required":False,
"risk_if_missing":"medium",
"description":"يجب توفير سكن ومواصلات أو بدل نقدي.",
"keywords":"بدل سكن; بدل نقل; housing allowance",
"reference":"نظام العمل"
}
]

new_df = pd.DataFrame(new_rows)

df = pd.concat([df, new_df], ignore_index=True)



print("Rows after adding:", len(df))

Rows after adding: 227

In [15]:
new_rows = [
{
"field":"resignation_definition",
"title_ar":"تعريف الاستقالة",
"category":"termination_exit",
"required":False,
"risk_if_missing":"medium",
"description":"الاستقالة طلب مكتوب يقدمه العامل إلى صاحب العمل لإنهاء العقد.",
"keywords":"استقالة; resignation; طلب استقالة",
"reference":"المادة 74"
},

{
"field":"resignation_delay",
"title_ar":"تأجيل قبول الاستقالة",
"category":"termination_exit",
"required":False,
"risk_if_missing":"medium",
"description":"يجوز لصاحب العمل تأجيل قبول الاستقالة لمدة لا تتجاوز 60 يوماً.",
"keywords":"تأجيل الاستقالة; resignation delay",
"reference":"المادة 75"
},

{
"field":"outsourcing_assignment",
"title_ar":"نظام الإسناد",
"category":"legal_compliance",
"required":False,
"risk_if_missing":"medium",
"description":"توفير عامل للعمل لدى غير صاحب العمل عبر منشأة مرخص لها.",
"keywords":"إسناد; outsourcing; assignment",
"reference":"نظام العمل"
},

{
"field":"non_saudi_contract_duration",
"title_ar":"مدة عقد العامل غير السعودي",
"category":"contract_terms",
"required":False,
"risk_if_missing":"medium",
"description":"يجب أن يكون عقد غير السعودي مكتوباً ومحدد المدة.",
"keywords":"غير سعودي; expatriate contract; مدة العقد",
"reference":"المادة 37"
},

{
"field":"training_contract_documentation",
"title_ar":"توثيق عقود التدريب",
"category":"legal_compliance",
"required":False,
"risk_if_missing":"medium",
"description":"يجب توثيق عقود التدريب على منصة قوى.",
"keywords":"عقد تدريب; منصة قوى; training contract",
"reference":"المادة 42"
},

{
"field":"disciplinary_grievance",
"title_ar":"التظلم من الجزاء التأديبي",
"category":"employer_rights",
"required":False,
"risk_if_missing":"medium",
"description":"يحق للعامل التظلم من الجزاء التأديبي خلال 30 يوماً.",
"keywords":"تظلم; grievance; جزاء تأديبي",
"reference":"المادة 72"
},

{
"field":"overtime_compensation_leave",
"title_ar":"تعويض العمل الإضافي بإجازة",
"category":"work_schedule",
"required":False,
"risk_if_missing":"medium",
"description":"يمكن التعويض عن ساعات العمل الإضافية بإجازات مدفوعة.",
"keywords":"عمل إضافي; overtime; compensatory leave",
"reference":"المادة 107"
},

{
"field":"paternity_leave",
"title_ar":"إجازة الأبوة",
"category":"leave_benefits",
"required":False,
"risk_if_missing":"low",
"description":"يستحق الأب إجازة مدفوعة لمدة 3 أيام عند ولادة طفل.",
"keywords":"إجازة الأبوة; paternity leave",
"reference":"المادة 113"
},

{
"field":"maternity_leave_duration",
"title_ar":"مدة إجازة الوضع",
"category":"leave_benefits",
"required":False,
"risk_if_missing":"low",
"description":"إجازة الوضع للمرأة العاملة مدتها 12 أسبوعاً.",
"keywords":"إجازة وضع; maternity leave",
"reference":"المادة 151"
}
]

In [ ]:
new_rows = [
    {
        "field": "paternity_leave",
        "title_ar": "إجازة الأبوة",
        "category": "leave_benefits",
        "required": "نعم",
        "risk_if_missing": "حرمان العامل من حق نظامي",
        "description": "يستحق العامل إجازة أبوة مدفوعة الأجر لمدة 3 أيام عند ولادة مولود، وتؤخذ خلال 7 أيام من تاريخ الولادة.",
        "keywords": "أبوة، مولود، 3 أيام",
        "reference": "المادة 113"
    },
    {
        "field": "hajj_leave",
        "title_ar": "إجازة الحج",
        "category": "leave_benefits",
        "required": "لا",
        "risk_if_missing": "نزاع في الاستحقاق",
        "description": "يستحق العامل إجازة مدفوعة الأجر لأداء فريضة الحج لمرة واحدة طوال مدة خدمته، وفق الشروط النظامية.",
        "keywords": "حج، إجازة، فريضة",
        "reference": "المادة 114"
    },
    {
        "field": "wage_protection_system",
        "title_ar": "نظام حماية الأجور",
        "category": "compensation",
        "required": "نعم",
        "risk_if_missing": "غرامات أو إيقاف خدمات",
        "description": "يلتزم صاحب العمل برفع بيانات الأجور وصرف الرواتب عبر الأنظمة المعتمدة لضمان حماية الأجور وعدم تأخيرها.",
        "keywords": "WPS، حماية الأجور، مدد",
        "reference": "قرار برنامج حماية الأجور"
    },
    {
        "field": "ramadan_working_hours",
        "title_ar": "ساعات العمل في رمضان",
        "category": "work_schedule",
        "required": "لا",
        "risk_if_missing": "مخالفة ساعات العمل الموسمية",
        "description": "تخفض ساعات العمل الفعلية للمسلمين خلال شهر رمضان إلى 6 ساعات يوميًا أو 36 ساعة أسبوعيًا.",
        "keywords": "رمضان، 6 ساعات، 36 ساعة",
        "reference": "المادة 98"
    },
    {
        "field": "flexible_work_arrangement",
        "title_ar": "ترتيبات العمل المرن",
        "category": "contract_terms",
        "required": "لا",
        "risk_if_missing": "نزاع على نمط العمل",
        "description": "يجوز الاتفاق على العمل المرن أو الجزئي أو بنظام الساعات وفق الأنظمة واللوائح المعتمدة.",
        "keywords": "مرن، flexible، جزئي",
        "reference": "تنظيم العمل المرن"
    },
    {
        "field": "electronic_contract_authentication",
        "title_ar": "توثيق العقد إلكترونيًا",
        "category": "general_provisions",
        "required": "نعم",
        "risk_if_missing": "ضعف الحجية أو عدم الامتثال",
        "description": "يجب توثيق عقد العمل إلكترونيًا عبر المنصات المعتمدة مثل منصة قوى وفق الأنظمة السارية.",
        "keywords": "قوى، توثيق، عقد إلكتروني",
        "reference": "المادة 17"
    },
    {
        "field": "probation_max_180_days",
        "title_ar": "الحد الأعلى لفترة التجربة",
        "category": "contract_terms",
        "required": "نعم",
        "risk_if_missing": "فترة تجربة غير مشروعة",
        "description": "يجوز الاتفاق على فترة تجربة على ألا تتجاوز 180 يومًا متى كان ذلك وفق الشروط النظامية.",
        "keywords": "تجربة، 180 يوم",
        "reference": "المادة 53"
    },
    {
        "field": "article77_compensation",
        "title_ar": "تعويض الفسخ غير المشروع",
        "category": "termination_exit",
        "required": "نعم",
        "risk_if_missing": "مطالبات مالية ونزاعات قضائية",
        "description": "يستحق الطرف المتضرر تعويضًا عند إنهاء العقد دون سبب مشروع وفق الضوابط المحددة نظامًا.",
        "keywords": "مادة 77، تعويض، فصل تعسفي",
        "reference": "المادة 77"
    },
    {
        "field": "article80_termination_cases",
        "title_ar": "حالات الفصل دون مكافأة أو إشعار",
        "category": "termination_exit",
        "required": "نعم",
        "risk_if_missing": "فصل غير مشروع",
        "description": "يجوز لصاحب العمل فصل العامل دون مكافأة أو إشعار في الحالات المحددة حصراً في النظام.",
        "keywords": "مادة 80، فصل فوري",
        "reference": "المادة 80"
    },
    {
        "field": "article81_employee_exit",
        "title_ar": "حق العامل في ترك العمل فورًا",
        "category": "termination_exit",
        "required": "نعم",
        "risk_if_missing": "حرمان العامل من حقه",
        "description": "يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه في الحالات المنصوص عليها نظامًا.",
        "keywords": "مادة 81، ترك العمل",
        "reference": "المادة 81"
    }
]

new_df = pd.DataFrame(new_rows)

df = df[~df["field"].isin(new_df["field"])].copy()

df = pd.concat([df, new_df], ignore_index=True)

df = df.sort_values(by=["category", "field"]).reset_index(drop=True)

print("تم تنظيف وإضافة البنود الجديدة بنجاح")
print("عدد الصفوف الحالي:", len(df))

تم تنظيف وإضافة البنود الجديدة بنجاح
عدد الصفوف الحالي: 231

In [ ]:
new_rows = [
{
"field":"employee_records_keeping",
"title_ar":"الاحتفاظ بسجلات العاملين",
"category":"legal_compliance",
"required":False,
"risk_if_missing":"medium",
"description":"يجب على صاحب العمل الاحتفاظ بسجلات وملفات العاملين في مكان العمل.",
"keywords":"سجلات العاملين; employee records; labor records",
"reference":"المادة 17"
},

{
"field":"work_schedule_display",
"title_ar":"إعلان جدول العمل في مكان ظاهر",
"category":"work_schedule",
"required":False,
"risk_if_missing":"low",
"description":"يجب على صاحب العمل عرض جدول العمل وساعات العمل والراحة في مكان ظاهر.",
"keywords":"جدول العمل; ساعات العمل; work schedule display",
"reference":"المادة 17"
},

{
"field":"contract_continuity_on_business_transfer",
"title_ar":"استمرار عقد العمل عند انتقال ملكية المنشأة",
"category":"contract_terms",
"required":False,
"risk_if_missing":"medium",
"description":"تستمر عقود العمل إذا انتقلت ملكية المنشأة إلى صاحب عمل جديد.",
"keywords":"انتقال ملكية المنشأة; business transfer; contract continuity",
"reference":"المادة 18"
}
]

new_df = pd.DataFrame(new_rows)

df = pd.concat([df, new_df], ignore_index=True)

df = df.drop_duplicates(subset=["field"], keep="first")

df = df.sort_values(by=["category","field"]).reset_index(drop=True)

print("تمت إضافة البنود بنجاح")
print("عدد الصفوف الحالي:", len(df))

تمت إضافة البنود بنجاح
عدد الصفوف الحالي: 227

In [ ]:

new_rows = [
{
"field": "contract_template_compliance",
"title_ar": "الالتزام بنموذج عقد العمل المعتمد",
"category": "contract_terms",
"required": False,
"risk_if_missing": "medium",
"description": "يجب أن يتوافق عقد العمل مع النموذج المعتمد من وزارة الموارد البشرية.",
"keywords": "نموذج عقد العمل، نموذج الوزارة، contract template",
"reference": "المادة 52"
},

{
"field": "employee_transfer_rules",
"title_ar": "نقل العامل لمكان عمل آخر",
"category": "employee_rights",
"required": False,
"risk_if_missing": "medium",
"description": "لا يجوز نقل العامل إلى مكان آخر يقتضي تغيير محل إقامته إلا بموافقته.",
"keywords": "نقل العامل، تغيير مكان العمل، employee transfer",
"reference": "المادة 58"
},

{
"field": "piecework_payment",
"title_ar": "الأجر بنظام القطعة أو الإنتاج",
"category": "compensation",
"required": False,
"risk_if_missing": "low",
"description": "يجوز الاتفاق على الأجر وفق نظام القطعة أو الإنتاج بما لا يخالف النظام.",
"keywords": "أجر القطعة، نظام الإنتاج، piecework salary",
"reference": "المادة 59"
},

{
"field": "job_change_restriction",
"title_ar": "عدم تكليف العامل بعمل مختلف",
"category": "employee_rights",
"required": False,
"risk_if_missing": "medium",
"description": "لا يجوز تكليف العامل بعمل يختلف اختلافاً جوهرياً عن عمله المتفق عليه.",
"keywords": "تغيير الوظيفة، تكليف بعمل آخر",
"reference": "المادة 60"
},

{
"field": "employer_obligations",
"title_ar": "التزامات صاحب العمل",
"category": "employer_obligations",
"required": True,
"risk_if_missing": "high",
"description": "يجب على صاحب العمل احترام العامل وعدم تشغيله سخرة وتوفير بيئة عمل مناسبة.",
"keywords": "التزامات صاحب العمل، employer duties",
"reference": "المادة 61"
},

{
"field": "employee_duties",
"title_ar": "واجبات العامل",
"category": "employee_obligations",
"required": True,
"risk_if_missing": "medium",
"description": "يجب على العامل أداء العمل بإخلاص والالتزام بتعليمات صاحب العمل.",
"keywords": "واجبات العامل، employee duties",
"reference": "المادة 65"
},

{
"field": "disciplinary_actions",
"title_ar": "الجزاءات التأديبية",
"category": "employee_obligations",
"required": False,
"risk_if_missing": "medium",
"description": "يجوز لصاحب العمل توقيع جزاءات تأديبية مثل الإنذار أو الخصم وفق النظام.",
"keywords": "جزاءات تأديبية، disciplinary action",
"reference": "المادة 66"
},

{
"field": "disciplinary_investigation",
"title_ar": "التحقيق قبل توقيع الجزاء",
"category": "legal_compliance",
"required": False,
"risk_if_missing": "medium",
"description": "لا يجوز توقيع جزاء تأديبي على العامل إلا بعد التحقيق معه.",
"keywords": "تحقيق تأديبي، disciplinary investigation",
"reference": "المادة 71"
},

{
"field": "non_compete_clause",
"title_ar": "شرط عدم المنافسة",
"category": "confidentiality_restrictions",
"required": False,
"risk_if_missing": "medium",
"description": "يجوز لصاحب العمل اشتراط عدم منافسة العامل بعد انتهاء العقد ضمن حدود محددة.",
"keywords": "عدم المنافسة، non compete",
"reference": "المادة 83"
},

{
"field": "end_of_service_award",
"title_ar": "مكافأة نهاية الخدمة",
"category": "termination_exit",
"required": True,
"risk_if_missing": "high",
"description": "يستحق العامل مكافأة نهاية خدمة تحسب وفق مدة خدمته في العمل.",
"keywords": "مكافأة نهاية الخدمة، end of service",
"reference": "المادة 84"
}
]

new_df = pd.DataFrame(new_rows)

df = df[~df["field"].isin(new_df["field"])]

df = pd.concat([df, new_df], ignore_index=True)

print("تمت إضافة البنود الجديدة بنجاح")
print("عدد الصفوف الحالي:", len(df))

تمت إضافة البنود الجديدة بنجاح
عدد الصفوف الحالي: 234

In [ ]:

new_rows = [
    {
        "field": "wage_official_currency",
        "title_ar": "دفع الأجر بالعملة الرسمية",
        "category": "compensation",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يجب دفع أجر العامل بالعملة الرسمية للبلد.",
        "keywords": "العملة الرسمية; دفع الأجر; official currency; wage payment",
        "reference": "المادة 90"
    },
    {
        "field": "wage_payment_on_time",
        "title_ar": "صرف الأجر في موعده",
        "category": "compensation",
        "required": True,
        "risk_if_missing": "high",
        "description": "يجب صرف أجر العامل في الموعد المحدد وفق النظام.",
        "keywords": "موعد صرف الأجر; صرف الراتب; pay on time; salary date",
        "reference": "المادة 90"
    },
    {
        "field": "wage_bank_transfer",
        "title_ar": "دفع الأجر عبر حساب بنكي",
        "category": "compensation",
        "required": False,
        "risk_if_missing": "medium",
        "description": "تدفع الأجور عبر حسابات العاملين في البنوك المعتمدة.",
        "keywords": "حساب بنكي; تحويل الراتب; bank transfer; payroll account",
        "reference": "المادة 90"
    },
    {
        "field": "piecework_or_production_wage",
        "title_ar": "تنظيم الأجر بنظام القطعة أو الإنتاج",
        "category": "compensation",
        "required": False,
        "risk_if_missing": "low",
        "description": "يجوز تنظيم الأجر على أساس القطعة أو الإنتاج وفق أحكام النظام.",
        "keywords": "القطعة; الإنتاج; piecework; production wage",
        "reference": "المادة 96"
    },
    {
        "field": "wage_deduction_rules",
        "title_ar": "القيود على خصم الأجر",
        "category": "compensation",
        "required": False,
        "risk_if_missing": "medium",
        "description": "لا يجوز الخصم من أجر العامل إلا في الحالات التي يجيزها النظام.",
        "keywords": "خصم الراتب; deductions; wage deduction",
        "reference": "المادة 92"
    },
    {
        "field": "loan_deduction_limit",
        "title_ar": "الحد الأعلى لخصم القروض من الأجر",
        "category": "compensation",
        "required": False,
        "risk_if_missing": "low",
        "description": "يخضع خصم القروض أو المبالغ المستحقة من أجر العامل للحدود النظامية.",
        "keywords": "قروض; خصم القرض; loan deduction",
        "reference": "المادة 92"
    },
    {
        "field": "daily_working_hours_limit",
        "title_ar": "الحد الأقصى لساعات العمل اليومية",
        "category": "work_schedule",
        "required": True,
        "risk_if_missing": "high",
        "description": "لا يجوز تشغيل العامل أكثر من الحد الأقصى لساعات العمل اليومية إلا وفق النظام.",
        "keywords": "ساعات العمل اليومية; daily working hours",
        "reference": "المادة 98"
    },
    {
        "field": "weekly_working_hours_limit",
        "title_ar": "الحد الأقصى لساعات العمل الأسبوعية",
        "category": "work_schedule",
        "required": True,
        "risk_if_missing": "high",
        "description": "لا يجوز تجاوز الحد الأقصى لساعات العمل الأسبوعية إلا وفق النظام.",
        "keywords": "ساعات العمل الأسبوعية; weekly working hours",
        "reference": "المادة 98"
    },
    {
        "field": "ramadan_working_hours",
        "title_ar": "تنظيم ساعات العمل في رمضان",
        "category": "work_schedule",
        "required": False,
        "risk_if_missing": "medium",
        "description": "تخفض ساعات العمل خلال شهر رمضان للمسلمين وفق النظام.",
        "keywords": "رمضان; ساعات العمل في رمضان; ramadan working hours",
        "reference": "المادة 98"
    },
    {
        "field": "overtime_pay_rules",
        "title_ar": "أجر العمل الإضافي",
        "category": "work_schedule",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يستحق العامل مقابلاً عن ساعات العمل الإضافية وفق النظام.",
        "keywords": "عمل إضافي; overtime pay; extra hours",
        "reference": "المادة 107"
    },
    {
        "field": "daily_rest_breaks",
        "title_ar": "فترات الراحة خلال يوم العمل",
        "category": "work_schedule",
        "required": False,
        "risk_if_missing": "medium",
        "description": "للعامل الحق في فترات راحة خلال يوم العمل وفق النظام.",
        "keywords": "فترات الراحة; break time; rest periods",
        "reference": "المادة 101"
    },
    {
        "field": "weekly_rest_day_rules",
        "title_ar": "الراحة الأسبوعية",
        "category": "work_schedule",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يستحق العامل يوماً للراحة الأسبوعية وفق ضوابط النظام.",
        "keywords": "الراحة الأسبوعية; weekly rest day",
        "reference": "المادة 104"
    },
    {
        "field": "annual_leave_entitlement",
        "title_ar": "الإجازة السنوية",
        "category": "leave_benefits",
        "required": True,
        "risk_if_missing": "high",
        "description": "يستحق العامل إجازة سنوية مدفوعة الأجر وفق النظام.",
        "keywords": "إجازة سنوية; annual leave; vacation",
        "reference": "المادة 109"
    },
    {
        "field": "annual_leave_postponement",
        "title_ar": "ترحيل الإجازة السنوية",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يجوز ترحيل الإجازة السنوية وفق الضوابط النظامية.",
        "keywords": "ترحيل الإجازة; postpone annual leave",
        "reference": "المادة 110"
    },
    {
        "field": "unused_leave_compensation",
        "title_ar": "تعويض الإجازة غير المستخدمة",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يستحق العامل أجر الإجازة عن الأيام غير المستخدمة وفق النظام.",
        "keywords": "تعويض الإجازة; unused leave compensation",
        "reference": "المادة 111"
    },
    {
        "field": "public_holidays_leave",
        "title_ar": "إجازات الأعياد والمناسبات الرسمية",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يستحق العامل إجازة بأجر كامل في الأعياد والمناسبات التي تحددها اللائحة.",
        "keywords": "الأعياد; المناسبات الرسمية; public holidays",
        "reference": "المادة 112"
    },
    {
        "field": "exam_leave",
        "title_ar": "إجازة الامتحانات الدراسية",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يجوز للعامل الحصول على إجازة لأداء الامتحانات وفق الضوابط النظامية.",
        "keywords": "إجازة الامتحانات; exam leave; study leave",
        "reference": "المادة 115"
    },
    {
        "field": "sick_leave_rules",
        "title_ar": "الإجازة المرضية",
        "category": "leave_benefits",
        "required": True,
        "risk_if_missing": "high",
        "description": "للعامل الحق في إجازة مرضية وفق المدد والأحكام النظامية.",
        "keywords": "إجازة مرضية; sick leave; medical leave",
        "reference": "المادة 117"
    },
    {
        "field": "unpaid_leave_rules",
        "title_ar": "الإجازة بدون أجر",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يجوز الاتفاق على إجازة بدون أجر وفق ما يقرره الطرفان.",
        "keywords": "إجازة بدون أجر; unpaid leave",
        "reference": "المادة 116"
    },
    {
        "field": "safe_work_environment",
        "title_ar": "توفير بيئة عمل آمنة",
        "category": "legal_compliance",
        "required": True,
        "risk_if_missing": "high",
        "description": "يلتزم صاحب العمل بتوفير بيئة عمل آمنة وخالية من المخاطر بقدر الإمكان.",
        "keywords": "بيئة عمل آمنة; work safety; safe environment",
        "reference": "المادة 121 بعد المائة"
    },
    {
        "field": "safety_equipment_provision",
        "title_ar": "توفير أدوات السلامة المهنية",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يلتزم صاحب العمل بتوفير أدوات ووسائل الوقاية والسلامة المهنية.",
        "keywords": "السلامة المهنية; معدات الوقاية; safety equipment",
        "reference": "المادة 122 بعد المائة"
    },
    {
        "field": "worker_safety_training",
        "title_ar": "تدريب العامل على مخاطر العمل",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يجب توعية العامل بمخاطر العمل وطرق الوقاية منها.",
        "keywords": "تدريب السلامة; مخاطر العمل; safety training",
        "reference": "المادة 123 بعد المائة"
    },
    {
        "field": "worker_follow_safety_rules",
        "title_ar": "التزام العامل بإجراءات السلامة",
        "category": "employee_obligations",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يلتزم العامل باتباع تعليمات السلامة والوقاية في مكان العمل.",
        "keywords": "تعليمات السلامة; worker safety compliance",
        "reference": "المادة 124 بعد المائة"
    },
    {
        "field": "work_injury_definition",
        "title_ar": "إصابة العمل",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "تحدد أحكام النظام ما يعد إصابة عمل وما يترتب عليها من حقوق.",
        "keywords": "إصابة العمل; work injury; occupational injury",
        "reference": "المادة 134 بعد المائة"
    },
    {
        "field": "employer_treatment_of_injury",
        "title_ar": "علاج العامل المصاب",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يلتزم صاحب العمل بعلاج العامل المصاب وفق أحكام النظام.",
        "keywords": "علاج العامل; work injury treatment",
        "reference": "المادة 133 بعد المائة"
    },
    {
        "field": "injury_disability_compensation",
        "title_ar": "تعويض العجز الناتج عن إصابة العمل",
        "category": "termination_exit",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يستحق العامل تعويضاً في حال العجز الناتج عن إصابة العمل وفق النظام.",
        "keywords": "تعويض العجز; disability compensation; work injury",
        "reference": "المادة 138 بعد المائة"
    },
    {
        "field": "death_compensation_work_injury",
        "title_ar": "تعويض الوفاة بسبب إصابة العمل",
        "category": "termination_exit",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يستحق المستحقون تعويضاً في حال وفاة العامل بسبب إصابة العمل وفق النظام.",
        "keywords": "تعويض الوفاة; death compensation; work injury",
        "reference": "المادة 138 بعد المائة"
    },
    {
        "field": "first_aid_availability",
        "title_ar": "توفير الإسعافات الأولية",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يجب توفير أدوات الإسعافات الأولية في مكان العمل.",
        "keywords": "إسعافات أولية; first aid",
        "reference": "المادة 142 بعد المائة"
    },
    {
        "field": "periodic_medical_exam",
        "title_ar": "الفحص الطبي الدوري",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يجوز أو يجب إجراء فحوصات طبية دورية للعاملين بحسب طبيعة العمل.",
        "keywords": "فحص طبي دوري; periodic medical exam",
        "reference": "المادة 143 بعد المائة"
    },
    {
        "field": "maternity_leave_rules",
        "title_ar": "إجازة الوضع",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "medium",
        "description": "للعاملة الحق في إجازة وضع وفق المدد والأحكام النظامية.",
        "keywords": "إجازة وضع; maternity leave",
        "reference": "المادة 151 بعد المائة"
    },
    {
        "field": "pregnant_worker_protection",
        "title_ar": "حماية المرأة الحامل في العمل",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "تتمتع العاملة الحامل بحماية نظامية أثناء الحمل والوضع.",
        "keywords": "حماية الحامل; pregnant worker protection",
        "reference": "المواد 151-157 بعد المائة"
    },
    {
        "field": "nursing_breaks",
        "title_ar": "فترات الراحة للمرأة المرضعة",
        "category": "leave_benefits",
        "required": False,
        "risk_if_missing": "low",
        "description": "يحق للعاملة المرضع فترات راحة إضافية لإرضاع طفلها وفق النظام.",
        "keywords": "رضاعة; nursing breaks; breastfeeding break",
        "reference": "المادة 154 بعد المائة"
    },
    {
        "field": "no_dismissal_due_to_pregnancy",
        "title_ar": "منع فصل العاملة بسبب الحمل أو الوضع",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "لا يجوز فصل العاملة أو إنذارها بالفصل بسبب الحمل أو الوضع وفق النظام.",
        "keywords": "فصل الحامل; maternity dismissal protection",
        "reference": "المادة 155 بعد المائة"
    },
    {
        "field": "minimum_working_age",
        "title_ar": "الحد الأدنى لعمر العمل",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يحدد النظام الحد الأدنى لسن العمل وشروط تشغيل الأحداث.",
        "keywords": "سن العمل; الحد الأدنى للعمر; minimum working age",
        "reference": "المادة 161 بعد المائة"
    },
    {
        "field": "juvenile_work_conditions",
        "title_ar": "شروط تشغيل الأحداث",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يشترط لتشغيل الأحداث التقيد بالأحكام الخاصة الواردة في النظام.",
        "keywords": "تشغيل الأحداث; juvenile employment",
        "reference": "المادة 162 بعد المائة"
    },
    {
        "field": "juvenile_working_hours",
        "title_ar": "ساعات عمل الأحداث",
        "category": "work_schedule",
        "required": False,
        "risk_if_missing": "medium",
        "description": "تخضع ساعات عمل الأحداث لقيود خاصة وفق النظام.",
        "keywords": "ساعات عمل الأحداث; juvenile working hours",
        "reference": "المادة 164 بعد المائة"
    },
    {
        "field": "no_hazardous_work_for_juveniles",
        "title_ar": "منع تشغيل الأحداث في الأعمال الخطرة",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "لا يجوز تشغيل الأحداث في الأعمال أو الصناعات الخطرة أو الضارة.",
        "keywords": "الأعمال الخطرة; الأحداث; hazardous work juveniles",
        "reference": "المادة 161 بعد المائة"
    }
]

new_df = pd.DataFrame(new_rows)

df = df[~df["field"].isin(new_df["field"])].copy()

df = pd.concat([df, new_df], ignore_index=True)

df = df.drop_duplicates(subset=["field"], keep="first")

df = df.sort_values(by=["category", "field"]).reset_index(drop=True)

print("تمت إضافة البنود الجديدة بنجاح")
print("عدد الصفوف الحالي:", len(df))

تمت إضافة البنود الجديدة بنجاح
عدد الصفوف الحالي: 268

In [44]:
new_row = {
    "field": "termination_due_to_absence",
    "title_ar": "إنهاء العقد بسبب الغياب",
    "category": "termination_exit",
    "required": False,
    "risk_if_missing": "medium",
    "description": "يجوز إنهاء عقد العامل إذا تغيب دون سبب مشروع أكثر من 30 يوماً خلال السنة أو أكثر من 15 يوماً متتالية بعد إنذاره.",
    "keywords": "الغياب; فصل بسبب الغياب; absence termination; article 80",
    "reference": "المادة 80"
}

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

print("تمت إضافة البند بنجاح")
print("عدد الصفوف الحالي:", len(df))

تمت إضافة البند بنجاح
عدد الصفوف الحالي: 269

In [ ]:
new_rows = [

{
"field": "max_work_hours",
"title_ar": "الحد الأقصى لساعات العمل",
"category": "working_hours",
"required": True,
"risk_if_missing": "high",
"description": "لا يجوز تشغيل العامل أكثر من 8 ساعات يومياً أو 48 ساعة أسبوعياً وفق نظام العمل.",
"keywords": "ساعات العمل; working hours; maximum hours; article 98",
"reference": "المادة 98"
},

{
"field": "overtime_pay",
"title_ar": "أجر العمل الإضافي",
"category": "salary",
"required": False,
"risk_if_missing": "medium",
"description": "يستحق العامل أجر ساعات العمل الإضافية بما يعادل أجر الساعة مضافاً إليه 50٪ من الأجر الأساسي.",
"keywords": "عمل إضافي; overtime pay; extra hours; article 107",
"reference": "المادة 107"
},

{
"field": "annual_leave",
"title_ar": "الإجازة السنوية",
"category": "leave",
"required": False,
"risk_if_missing": "medium",
"description": "يستحق العامل إجازة سنوية لا تقل عن 21 يوماً وتزيد إلى 30 يوماً إذا أمضى خمس سنوات في الخدمة.",
"keywords": "إجازة سنوية; annual leave; vacation; article 109",
"reference": "المادة 109"
},

{
"field": "social_insurance_registration",
"title_ar": "التسجيل في التأمينات الاجتماعية",
"category": "employment_rights",
"required": False,
"risk_if_missing": "high",
"description": "يلتزم صاحب العمل بتسجيل العامل في المؤسسة العامة للتأمينات الاجتماعية وفق الأنظمة المعمول بها.",
"keywords": "تأمينات اجتماعية; social insurance; gosi registration",
"reference": "نظام التأمينات الاجتماعية"
}

]

new_df = pd.DataFrame(new_rows)

df = df[~df["field"].isin(new_df["field"])]

df = pd.concat([df, new_df], ignore_index=True)

print("تمت إضافة البنود الجديدة بنجاح")
print("عدد الصفوف الحالي:", len(df))

تمت إضافة البنود الجديدة بنجاح
عدد الصفوف الحالي: 271

In [47]:
df[df["field"] == "termination_due_to_absence"]

,field,title_ar,category,required,risk_if_missing,description,keywords,reference
268,termination_due_to_absence,إنهاء العقد بسبب الغياب,termination_exit,False,medium,يجوز إنهاء عقد العامل إذا تغيب دون سبب مشروع أ...,الغياب; فصل بسبب الغياب; absence termination; ...,المادة 80

In [ ]:

df = pd.concat([df, new_df], ignore_index=True)

df = df.sort_values(by=["category", "field"]).reset_index(drop=True)

print("تمت إضافة البنود الجديدة بنجاح")
print("عدد الصفوف الحالي:", len(df))

تمت إضافة البنود الجديدة بنجاح
عدد الصفوف الحالي: 227

In [49]:
dup = df["field"].value_counts()
print(dup[dup > 1])

Series([], Name: count, dtype: int64)

In [35]:
df[df.duplicated(subset="field", keep=False)].sort_values("field")

Empty DataFrame
Columns: [field, title_ar, category, required, risk_if_missing, description, keywords, reference]
Index: []

In [31]:
df = df.drop_duplicates(subset="field", keep="first")

print("عدد الصفوف بعد حذف التكرار:", len(df))

عدد الصفوف بعد حذف التكرار: 227

In [91]:
df.isnull().sum()

field              0
title_ar           0
category           0
required           0
risk_if_missing    0
description        0
keywords           0
reference          0
dtype: int64

In [3]:
import pandas as pd

df = pd.read_excel("labor_contracts_master_clean.xlsx")

print(df.head())

                    field                      title_ar      category  \
0              allowances                       البدلات  compensation
1  annual_bonus_non_saudi  العلاوة السنوية لغير السعودي  compensation
2               bank_name                     اسم البنك  compensation
3            basic_salary                 الأجر الأساسي  compensation
4       commission_clause                      العمولات  compensation

  required                        risk_if_missing  \
0       لا                حرمان من مستحقات إضافية
1       لا                              نزاع مالي
2       لا                       تعثر صرف الرواتب
3      نعم  بطلان العقد ومخالفة صريحة لنظام العمل
4       لا                     نزاع على الاستحقاق

                                         description               keywords  \
0                       تحديد بدل سكن أو نقل أو غيره        بدل، allowances
1                 علاوة سنوية لا تتجاوز 5% من الراتب            علاوة سنوية
2                  اسم بنك العامل لتحويل الراتب إليه                    بنك
3  المبلغ المالي الثابت المتفق عليه مقابل العمل س...  أجر، راتب، ريال سعودي
4  تنظيم نسبة العمولة وآلية وموعد استحقاقها إذا ا...      عمولة، commission

                                           reference
0                                          المادة 18
1                                  نموذج غير السعودي
2  نموذج عقد العمل – معلومات الحساب البنكي للطرف ...
3                                          المادة 18
4                      نموذج عقد العمل – الفقرة 9.13

In [10]:
df = df.drop_duplicates(subset=["field"], keep="first")

print("عدد الصفوف بعد حذف التكرار:", len(df))

dup = df["field"].value_counts()
print(dup[dup > 1])

عدد الصفوف بعد حذف التكرار: 220
Series([], Name: count, dtype: int64)

In [58]:
df.to_excel("labor_contracts_master_clean.xlsx", index=False)
print("تم الحفظ بنجاح")

تم الحفظ بنجاح

In [14]:
import os
print(os.getcwd())

c:\Users\lamaa\OneDrive\Documents\Final project\capstone-project-team\untitled folder 4

In [52]:
print(df["category"].value_counts())

category
legal_compliance                52
compensation                    34
leave_benefits                  28
parties                         27
termination_exit                24
contract_terms                  20
general_provisions              18
work_schedule                   17
employee_obligations            12
employer_rights                 10
job_information                  6
customer_rights                  4
governance                       4
confidentiality_restrictions     3
operations                       3
employee_rights                  2
working_hours                    1
leave                            1
salary                           1
marketing_compliance             1
security                         1
employer_obligations             1
employment_rights                1
Name: count, dtype: int64

In [53]:
df["category"] = df["category"].replace({
    "leave": "leave_benefits",
    "salary": "compensation",
    "working_hours": "work_schedule",
    "employee_rights": "employment_rights",
    "employer_obligations": "employer_rights"
})

In [54]:
print(df["category"].value_counts())

category
legal_compliance                52
compensation                    35
leave_benefits                  29
parties                         27
termination_exit                24
contract_terms                  20
general_provisions              18
work_schedule                   18
employee_obligations            12
employer_rights                 11
job_information                  6
governance                       4
customer_rights                  4
confidentiality_restrictions     3
employment_rights                3
operations                       3
marketing_compliance             1
security                         1
Name: count, dtype: int64

In [55]:
drop_categories = [
    "customer_rights",
    "marketing_compliance"
]

df = df[~df["category"].isin(drop_categories)]

In [56]:
print(df["category"].value_counts())

category
legal_compliance                52
compensation                    35
leave_benefits                  29
parties                         27
termination_exit                24
contract_terms                  20
general_provisions              18
work_schedule                   18
employee_obligations            12
employer_rights                 11
job_information                  6
governance                       4
confidentiality_restrictions     3
employment_rights                3
operations                       3
security                         1
Name: count, dtype: int64

In [57]:
df["category"] = df["category"].replace({
    "employment_rights": "legal_compliance"
})

df = df.drop_duplicates(subset=["field"]).reset_index(drop=True)

print("عدد البنود النهائي:", len(df))
print(df["category"].value_counts())

عدد البنود النهائي: 266
category
legal_compliance                55
compensation                    35
leave_benefits                  29
parties                         27
termination_exit                24
contract_terms                  20
general_provisions              18
work_schedule                   18
employee_obligations            12
employer_rights                 11
job_information                  6
governance                       4
confidentiality_restrictions     3
operations                       3
security                         1
Name: count, dtype: int64

In [64]:
df.to_excel("labor_contracts_final_clean.xlsx", index=False)

print("تم إنشاء ملف نظيف جديد")

تم إنشاء ملف نظيف جديد

In [61]:
df[df.duplicated(subset=["field"])]

Empty DataFrame
Columns: [field, title_ar, category, required, risk_if_missing, description, keywords, reference]
Index: []

In [62]:
df["category"].value_counts()

category
legal_compliance                55
compensation                    35
leave_benefits                  29
parties                         27
termination_exit                24
contract_terms                  20
general_provisions              18
work_schedule                   18
employee_obligations            12
employer_rights                 11
job_information                  6
governance                       4
confidentiality_restrictions     3
operations                       3
security                         1
Name: count, dtype: int64

In [63]:
print("عدد البنود النهائي:", len(df))

عدد البنود النهائي: 266

In [65]:
test_df = pd.read_excel("labor_contracts_final_clean.xlsx")

print(len(test_df))

266

# ==================================

 # NDA

In [ ]:

nda_df = df[
    (df["category"] == "confidentiality_restrictions") |
    (df["field"].str.contains("confidential|non_compete|nda", case=False, na=False)) |
    (df["keywords"].str.contains("confidential|عدم الإفصاح|سرية", case=False, na=False))
]

nda_df = nda_df[[
    "field",
    "title_ar",
    "category",
    "required",
    "risk_if_missing",
    "description",
    "keywords",
    "reference"
]]

nda_df.to_excel("nda_clauses_clean.xlsx", index=False)

print("تم إنشاء ملف NDA بنفس ترتيب لائحة العمل")
print("عدد البنود:", len(nda_df))

تم إنشاء ملف NDA بنفس ترتيب لائحة العمل
عدد البنود: 9

In [ ]:
drop_titles = [
    "التقويم الهجري المعتمد",
    "معايير جودة الخدمة",
    "الحضور والغياب",
    "مخالفات الدوام والانضباط",
    "نظام الحضور والانصراف"
]

df = df[~df["title_ar"].isin(drop_titles)].reset_index(drop=True)

df.to_excel("nda_clauses_clean.xlsx", index=False)

print("تم حذف البنود غير المتعلقة بـ NDA وحفظ الملف الجديد")
print("عدد الصفوف بعد الحذف:", len(df))

تم حذف البنود غير المتعلقة بـ NDA وحفظ الملف الجديد
عدد الصفوف بعد الحذف: 261

In [68]:
labor_df = pd.read_excel("labor_contracts_final_clean.xlsx")
print("عدد صفوف ملف العمل:", len(labor_df))

عدد صفوف ملف العمل: 266

In [69]:
df = pd.read_excel("labor_contracts_final_clean.xlsx")
print("تمت إعادة تحميل ملف العمل")
print("عدد الصفوف:", len(df))

تمت إعادة تحميل ملف العمل
عدد الصفوف: 266

In [70]:
nda_df = df[
    (df["category"] == "confidentiality_restrictions") |
    (df["field"].str.contains("confidential|non_compete|nda", case=False, na=False)) |
    (df["keywords"].str.contains("confidential|عدم الإفصاح|سرية", case=False, na=False))
].copy()

print("عدد بنود NDA قبل التنظيف:", len(nda_df))

عدد بنود NDA قبل التنظيف: 9

In [ ]:

new_rows = [
    {
        "field": "confidential_information_definition",
        "title_ar": "تعريف المعلومات السرية",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "تحديد ما تعتبره الاتفاقية معلومات سرية مثل البيانات المالية والتقنية وقوائم العملاء والمعلومات التشغيلية.",
        "keywords": "معلومات سرية; confidential information; بيانات; قوائم العملاء; معلومات تقنية",
        "reference": "المادة 1"
    },
    {
        "field": "non_disclosure_obligation",
        "title_ar": "التزام عدم الإفصاح",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "يلتزم الطرف المستلم بعدم كشف أو نشر أو مشاركة المعلومات السرية مع أي طرف غير مصرح له.",
        "keywords": "عدم الإفصاح; non disclosure; NDA; سرية",
        "reference": "المادة 4"
    },
    {
        "field": "confidential_information_use_scope",
        "title_ar": "استخدام المعلومات السرية للغرض المتفق عليه",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "medium",
        "description": "تستخدم المعلومات السرية فقط في نطاق العمل أو المشروع أو الغرض المحدد في الاتفاقية.",
        "keywords": "استخدام المعلومات; scope of use; purpose limitation",
        "reference": "المادة 3"
    },
    {
        "field": "confidentiality_exceptions",
        "title_ar": "استثناءات السرية",
        "category": "confidentiality_restrictions",
        "required": False,
        "risk_if_missing": "medium",
        "description": "تحدد الحالات التي لا تعتبر فيها المعلومات سرية مثل المعلومات العامة أو المطورة بشكل مستقل أو المطلوبة نظاماً.",
        "keywords": "استثناءات السرية; confidentiality exceptions; public information",
        "reference": "المادة 6"
    },
    {
        "field": "return_or_destroy_confidential_material",
        "title_ar": "إعادة أو إتلاف المعلومات والمستندات السرية",
        "category": "confidentiality_restrictions",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يلتزم الطرف المستلم بإعادة أو إتلاف المعلومات والمستندات السرية عند انتهاء العلاقة أو عند طلب الطرف المالك.",
        "keywords": "إعادة المستندات; إتلاف المعلومات; return confidential material",
        "reference": "المادة 7"
    },
    {
        "field": "intellectual_property_ownership",
        "title_ar": "ملكية المعلومات والملكية الفكرية",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "تبقى ملكية المعلومات السرية والحقوق الفكرية المرتبطة بها للطرف المالك لها، ولا ينتج عن الإفصاح أي نقل للملكية.",
        "keywords": "ملكية فكرية; intellectual property; ownership; confidential information",
        "reference": "المادة 8"
    },
    {
        "field": "nda_breach_consequences",
        "title_ar": "الإخلال بالاتفاقية والتعويض",
        "category": "legal_compliance",
        "required": True,
        "risk_if_missing": "high",
        "description": "في حال خرق الاتفاقية يحق للطرف المتضرر المطالبة بالتعويض واتخاذ الإجراءات القانونية المناسبة.",
        "keywords": "إخلال; breach; violation; تعويض",
        "reference": "المادة 10"
    },
    {
        "field": "nda_duration",
        "title_ar": "مدة سريان الاتفاقية",
        "category": "contract_terms",
        "required": True,
        "risk_if_missing": "medium",
        "description": "تحدد مدة سريان الاتفاقية واستمرار الالتزامات المتعلقة بالسرية بعد انتهاء العلاقة عند النص على ذلك.",
        "keywords": "مدة الاتفاقية; duration; term; survival",
        "reference": "المادة 12"
    },
    {
        "field": "governing_law_and_jurisdiction",
        "title_ar": "القانون الواجب التطبيق والاختصاص القضائي",
        "category": "legal_compliance",
        "required": True,
        "risk_if_missing": "medium",
        "description": "تخضع الاتفاقية لأنظمة المملكة العربية السعودية وتختص الجهات القضائية السعودية بالنظر في النزاعات.",
        "keywords": "القانون الواجب التطبيق; jurisdiction; Saudi law; اختصاص قضائي",
        "reference": "المادة 13"
    }
]

new_df = pd.DataFrame(new_rows)

try:
    nda_df
except NameError:
    nda_df = pd.DataFrame(columns=new_df.columns)

nda_df = nda_df[~nda_df["field"].isin(new_df["field"])].copy()

nda_df = pd.concat([nda_df, new_df], ignore_index=True)

nda_df = nda_df[[
    "field",
    "title_ar",
    "category",
    "required",
    "risk_if_missing",
    "description",
    "keywords",
    "reference"
]]

nda_df.to_excel("nda_clauses_clean.xlsx", index=False)

print("تمت إضافة بنود NDA المهمة بنجاح")
print("عدد بنود NDA:", len(nda_df))

تمت إضافة بنود NDA المهمة بنجاح
عدد بنود NDA: 13

In [73]:
extra_rows = [
{
"field": "information_accuracy_disclaimer",
"title_ar": "عدم ضمان دقة المعلومات",
"category": "legal_compliance",
"required": False,
"risk_if_missing": "medium",
"description": "لا يضمن الطرف الأول دقة أو اكتمال المعلومات المقدمة للطرف الثاني.",
"keywords": "دقة المعلومات; disclaimer; accuracy",
"reference": "المادة 2"
},

{
"field": "representatives_confidentiality",
"title_ar": "التزام الموظفين والممثلين بالسرية",
"category": "confidentiality_restrictions",
"required": True,
"risk_if_missing": "high",
"description": "يلتزم موظفو أو مستشارو الطرف الثاني بالحفاظ على سرية المعلومات.",
"keywords": "representatives; employees; confidentiality",
"reference": "المادة 3"
},

{
"field": "copy_or_reproduce_restriction",
"title_ar": "منع نسخ أو تصوير المعلومات",
"category": "confidentiality_restrictions",
"required": True,
"risk_if_missing": "high",
"description": "يمنع نسخ أو تصوير أو إعادة استخدام المعلومات السرية دون إذن.",
"keywords": "copy; reproduce; information protection",
"reference": "المادة 4"
},

{
"field": "legal_disclosure_exception",
"title_ar": "الإفصاح المسموح قانونياً",
"category": "legal_compliance",
"required": False,
"risk_if_missing": "medium",
"description": "يسمح بالإفصاح عن المعلومات إذا كان ذلك مطلوباً بموجب القانون.",
"keywords": "legal disclosure; law requirement",
"reference": "المادة 6"
},

{
"field": "breach_notification",
"title_ar": "الإبلاغ عن خرق الاتفاقية",
"category": "legal_compliance",
"required": True,
"risk_if_missing": "high",
"description": "يلتزم الطرف الثاني بإبلاغ الطرف الأول فور حدوث أي خرق للاتفاقية.",
"keywords": "breach notification; violation",
"reference": "المادة 9"
},

{
"field": "no_waiver_clause",
"title_ar": "عدم التنازل عن الحقوق",
"category": "contract_terms",
"required": False,
"risk_if_missing": "low",
"description": "عدم تطبيق أي بند لا يعني التنازل عن باقي البنود.",
"keywords": "no waiver; legal rights",
"reference": "المادة 15"
},

{
"field": "language_priority",
"title_ar": "اعتماد اللغة العربية للاتفاقية",
"category": "contract_terms",
"required": False,
"risk_if_missing": "low",
"description": "في حال وجود نسختين عربية وإنجليزية تعتمد النسخة العربية في التفسير.",
"keywords": "language priority; Arabic version",
"reference": "المادة 14"
}
]

extra_df = pd.DataFrame(extra_rows)

nda_df = pd.concat([nda_df, extra_df], ignore_index=True)

nda_df.to_excel("nda_clauses_clean.xlsx", index=False)

print("تمت إضافة البنود الجديدة")
print("عدد بنود NDA:", len(nda_df))

تمت إضافة البنود الجديدة
عدد بنود NDA: 20

In [ ]:

new_rows = [
    {
        "field": "personal_data_definition",
        "title_ar": "تعريف البيانات الشخصية",
        "category": "legal_compliance",
        "required": True,
        "risk_if_missing": "high",
        "description": "يقصد بالبيانات الشخصية كل بيان من شأنه أن يؤدي إلى معرفة الفرد على وجه التحديد أو يجعل التعرف عليه ممكناً بصورة مباشرة أو غير مباشرة.",
        "keywords": "البيانات الشخصية; personal data; تعريف البيانات",
        "reference": "المادة 1"
    },
    {
        "field": "sensitive_personal_data",
        "title_ar": "البيانات الشخصية الحساسة",
        "category": "legal_compliance",
        "required": True,
        "risk_if_missing": "high",
        "description": "تشمل البيانات الحساسة ما يدل على الأصل العرقي أو القبلي أو المعتقد أو البيانات الصحية أو الوراثية أو الائتمانية أو البيومترية وغيرها مما يحدده النظام.",
        "keywords": "بيانات حساسة; sensitive data; صحية; بيومترية; وراثية; ائتمانية",
        "reference": "المادة 1"
    },
    {
        "field": "data_subject_access_right",
        "title_ar": "حق صاحب البيانات في الوصول إلى بياناته",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يحق لصاحب البيانات الشخصية الوصول إلى بياناته الشخصية المتوافرة لدى جهة التحكم وفق الضوابط النظامية.",
        "keywords": "حق الوصول; access right; صاحب البيانات",
        "reference": "المادة 4"
    },
    {
        "field": "data_correction_right",
        "title_ar": "حق تصحيح البيانات الشخصية",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يحق لصاحب البيانات الشخصية طلب تصحيح بياناته الشخصية أو تحديثها أو إتمامها.",
        "keywords": "تصحيح البيانات; correction; update personal data",
        "reference": "المادة 4"
    },
    {
        "field": "data_deletion_after_purpose",
        "title_ar": "حذف البيانات بعد انتهاء الغرض منها",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "على جهة التحكم إتلاف البيانات الشخصية بعد انتهاء الغرض من جمعها، ما لم يوجد مسوغ نظامي للاحتفاظ بها لمدة محددة.",
        "keywords": "إتلاف البيانات; حذف البيانات; deletion; end of purpose",
        "reference": "المادة 18"
    },
    {
        "field": "data_retention_policy",
        "title_ar": "سياسة الاحتفاظ بالبيانات",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "يجوز الاحتفاظ بالبيانات الشخصية بعد انتهاء الغرض منها إذا وجد مسوغ نظامي أو كانت مرتبطة بقضية منظورة أو مدة احتفاظ محددة نظاماً.",
        "keywords": "الاحتفاظ بالبيانات; retention policy; data retention",
        "reference": "المادة 18"
    },
    {
        "field": "personal_data_security_measures",
        "title_ar": "إجراءات حماية البيانات الشخصية",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "على جهة التحكم اتخاذ ما يلزم من إجراءات ووسائل تنظيمية وإدارية وتقنية لضمان المحافظة على البيانات الشخصية عند نقلها أو تخزينها أو معالجتها.",
        "keywords": "حماية البيانات; security measures; data protection",
        "reference": "المادة 19"
    },
    {
        "field": "data_breach_notification",
        "title_ar": "الإبلاغ عن اختراق أو تسرب البيانات",
        "category": "legal_compliance",
        "required": True,
        "risk_if_missing": "high",
        "description": "على جهة التحكم إشعار الجهة المختصة وصاحب البيانات عند حدوث تسرب أو تلف أو وصول غير مشروع إلى البيانات الشخصية إذا ترتب عليه ضرر أو تعارض مع الحقوق أو المصالح.",
        "keywords": "اختراق البيانات; تسرب البيانات; breach notification; data leak",
        "reference": "المادة 20"
    },
    {
        "field": "cross_border_data_transfer",
        "title_ar": "نقل البيانات الشخصية خارج المملكة",
        "category": "legal_compliance",
        "required": False,
        "risk_if_missing": "medium",
        "description": "يجوز نقل البيانات الشخصية خارج المملكة أو الإفصاح عنها خارجها وفق الحالات والضوابط النظامية المحددة.",
        "keywords": "نقل البيانات خارج المملكة; cross-border transfer; data transfer",
        "reference": "المادة 29"
    },
    {
        "field": "post_employment_data_confidentiality",
        "title_ar": "الالتزام بسرية البيانات حتى بعد انتهاء العلاقة الوظيفية أو التعاقدية",
        "category": "confidentiality_restrictions",
        "required": True,
        "risk_if_missing": "high",
        "description": "يلتزم من يباشر أعمال معالجة البيانات الشخصية بالمحافظة على الأسرار المتعلقة بالبيانات حتى بعد انتهاء علاقته الوظيفية أو التعاقدية.",
        "keywords": "سرية بعد انتهاء العلاقة; post employment confidentiality; data secrecy",
        "reference": "المادة 41"
    }
]

new_df = pd.DataFrame(new_rows)

try:
    nda_df
except NameError:
    nda_df = pd.DataFrame(columns=new_df.columns)

nda_df = nda_df[~nda_df["field"].isin(new_df["field"])].copy()

nda_df = pd.concat([nda_df, new_df], ignore_index=True)

nda_df = nda_df[[
    "field",
    "title_ar",
    "category",
    "required",
    "risk_if_missing",
    "description",
    "keywords",
    "reference"
]]

nda_df.to_excel("nda_clauses_clean.xlsx", index=False)

print("تمت إضافة بنود PDPL إلى ملف NDA بنجاح")
print("عدد بنود NDA الحالي:", len(nda_df))

تمت إضافة بنود PDPL إلى ملف NDA بنجاح
عدد بنود NDA الحالي: 30

In [ ]:
import pandas as pd
import json

file_path = r"C:\Users\lamaa\OneDrive\Documents\Final project\capstone-project-team\untitled folder 4\labor_contracts_final_clean.xlsx"

df = pd.read_excel(file_path)

data = df.to_dict(orient="records")

json_path = r"C:\Users\lamaa\OneDrive\Documents\Final project\capstone-project-team\untitled folder 4\labor_contracts_final_clean.json"

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("تم تحويل ملف العمل إلى JSON بنجاح")
print("عدد البنود:", len(data))

تم تحويل ملف العمل إلى JSON بنجاح
عدد البنود: 266

In [ ]:
import pandas as pd
import json

excel_path = r"C:\Users\lamaa\OneDrive\Documents\Final project\capstone-project-team\untitled folder 4\nda_clauses_master_clean1.xlsx"

df = pd.read_excel(excel_path)

data = df.to_dict(orient="records")

json_path = r"C:\Users\lamaa\OneDrive\Documents\Final project\capstone-project-team\untitled folder 4\nda_clauses_master_clean1.json"

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("تم تحويل ملف NDA إلى JSON بنجاح")
print("عدد البنود:", len(data))
print("مكان الملف:", json_path)

تم تحويل ملف NDA إلى JSON بنجاح
عدد البنود: 65
مكان الملف: C:\Users\lamaa\OneDrive\Documents\Final project\capstone-project-team\untitled folder 4\nda_clauses_master_clean1.json

## Summary

The datasets have been cleaned and standardized.

Final datasets:
- labor_contracts_final_clean
- nda_clauses_master_clean1